# Pre-processing Allocation data for WaDE upload.
- Purpose:  To pre-process the data into one main file for simple DataFrame creation and extraction

In [1]:
import sys
print(sys.executable)

C:\Users\rjame\anaconda3\envs\wade_data_project\python.exe

In [2]:
import os
import sys
print(os.environ['CONDA_DEFAULT_ENV'])
print(sys.version)

wade_data_project
3.13.5 | packaged by conda-forge | (main, Jun 16 2025, 08:20:19) [MSC v.1943 64 bit (AMD64)]

In [3]:
# Needed Libraries / Modules

# ---- working with data ----
import numpy as np  # mathematical array manipulation
import pandas as pd  # data structure and data analysis
import geopandas as gpd  # geo-data structure and data analysis

# ---- visualization ----
import matplotlib.pyplot as plt  # plotting library
import seaborn as sns  # plotting library

# ---- API data retrieval ----
import requests  # http requests
import json  # JSON parse

# ---- Cleanup ----
import re  # string regular expression manipulation
from datetime import datetime  # date and time manipulation
pd.set_option('display.max_columns', 999)  # How to display all columns of a Pandas DataFrame in Jupyter Notebook
pd.set_option('display.float_format', lambda x: '%.5f' % x)  # suppress scientific notation in Pandas

In [4]:
# ---- working directory ----
workingDirString = "G:/Shared drives/WaDE Data/WaDE Data Folder/Colorado/WaterAllocation" # set working directory folder string here
os.chdir(workingDirString)
print(f'The working Directory is:', workingDirString)

The working Directory is: G:/Shared drives/WaDE Data/WaDE Data Folder/Colorado/WaterAllocation

## Point of Diversion Data

In [5]:
# Input File
FI_PoD = "RawInputData/DWR_Water_Right_-_Net_Amounts_20260206.zip"
dfinPOD = pd.read_csv(FI_PoD, encoding = "ISO-8859-1").replace(np.nan, "")

# WaDE UUID tracker for data assessment
if 'WaDEUUID' not in dfinPOD:
    dfinPOD['WaDEUUID'] = "d" + dfinPOD.index.astype(str)
    dfinPOD.to_csv('RawInputData/DWR_Water_Right_-_Net_Amounts_20260206.zip', compression=dict(method='zip', archive_name='DWR_Water_Right_-_Net_Amounts_20260206.csv'), index=False)

print(len(dfinPOD))
dfinPOD.head()

C:\Users\rjame\AppData\Local\Temp\ipykernel_19300\3845759418.py:3: DtypeWarning: Columns (12,30) have mixed types. Specify dtype option on import or set low_memory=False.
  dfinPOD = pd.read_csv(FI_PoD, encoding = "ISO-8859-1").replace(np.nan, "")

173128

,WDID,Structure Name,Structure Type,Water Source,GNIS ID,Stream Mile,DIV,WD,County,Q10,Q40,Q160,Section,Township,Range,PM,CoordsEW,CoordsEW Dir,CoordsNS,CoordsNS Dir,UTM x,UTM y,Latitude,Longitude,Location Accuracy,Adjudication Date,Previous Adj Date,Appropriation Date,Admin No,Order No,Priority No,Associated Case Numbers,Decreed Uses,Net Absolute,Net Conditional,Net APEX Absolute,Net APEX Conditional,Decreed Units,Seasonal Limits,Comments,Modified,More Information,Location,WaDEUUID
0,5803688,GOLF COURSE POND,Reservoir,YAMPA RIVER,169566.00000,,6,58,ROUTT,,NE,NW,10.00000,5.0 N,84.0 W,S,,,,,347362.00000,4474934.00000,40.41105,-106.79897,Digitized,12/31/1998,12/31/1997,08/28/1998,54296.00000,0,,98CW0039,123568A,0.00000,62.00000,0.00000,0.00000,A,No,FILL. RATE OF DIVERSION INTO POND IS LIMITED T...,02/02/2026 03:03:00 PM,https://dwr.state.co.us/Tools/WaterRights/NetA...,"(40.411047, -106.79897)",d0
1,5805086,CR WELL NO. 2,Well,GROUNDWATER: YAMPA RIVER,169566.00000,,6,58,ROUTT,,NW,SE,4.00000,5.0 N,84.0 W,S,,,,,346012.00000,4475954.00000,40.41998,-106.81512,GPS,12/31/1998,12/31/1997,08/28/1998,54296.00000,0,,"06CW0016, 98CW0039",1238,0.12300,0.15550,0.00000,0.83550,C,No,"ALT PTS @ CR WELL 1A & 1, 3-4; LIMIT 500 GPM &...",02/02/2026 02:44:00 PM,https://dwr.state.co.us/Tools/WaterRights/NetA...,"(40.419983, -106.81512)",d1
2,4303802,CORRAL GULCH LOWER SITE RESERVOIR,Reservoir,CORRAL GULCH,171797.00000,4.84000,6,43,RIO BLANCO,,NW,SW,34.00000,1.0 S,99.0 W,S,830.00000,W,2140.00000,S,201086.90000,4424597.90000,39.91876,-108.49729,Spotted from section lines,12/31/2003,12/31/2002,05/21/2002,55882.55658,0,,03CW0160,348A,0.00000,23.00000,0.00000,0.00000,A,No,TOGETHER WITH THE RIGHT TO FILL & REFILL,02/02/2026 05:07:00 PM,https://dwr.state.co.us/Tools/WaterRights/NetA...,"(39.918762, -108.497287)",d2
3,5800627,ENTERPRISE DITCH,Ditch,WALTON CREEK,172751.00000,4.07000,6,58,ROUTT,,NW,NE,10.00000,5.0 N,84.0 W,S,,,,,347657.00000,4474720.00000,40.40917,-106.79544,GPS,09/22/1892,,10/08/1887,13795.00000,0,(38)37,"09/22/1892, 01CW0109",1X,14.00000,0.00000,0.00000,0.00000,C,No,CA3956 CHG PT OF DIVERSION & ADD ALL BENEFICIA...,02/02/2026 03:16:00 PM,https://dwr.state.co.us/Tools/WaterRights/NetA...,"(40.409174, -106.795444)",d3
4,5800627,ENTERPRISE DITCH,Ditch,WALTON CREEK,172751.00000,4.07000,6,58,ROUTT,,NW,NE,10.00000,5.0 N,84.0 W,S,,,,,347657.00000,4474720.00000,40.40917,-106.79544,GPS,12/31/1998,12/31/1997,08/28/1998,54296.00000,0,,"98CW0039, 06CW0016",1238,1.00000,0.00000,0.00000,1.00000,C,No,CATAMOUNT ENLARGEMENT; AP @ HIGHLINE BEAVER DI...,02/02/2026 03:16:00 PM,https://dwr.state.co.us/Tools/WaterRights/NetA...,"(40.409174, -106.795444)",d4

In [6]:
#Creating Beneficial Use.
#Need to split CO abbreviatoin strings to a workable format.

BenUseDict = {
"0" : "Storage",
"1" : "Irrigation",
"2" : "Municipal",
"3" : "Commercial",
"4" : "Industrial",
"5" : "Recreation",
"6" : "Fishery",
"7" : "Fire",
"8" : "Domestic",
"9" : "Stock",
"A" : "Augmentation",
"B" : "Export from Basin",
"C" : "Cumulative Accretion to River",
"D" : "Cumulative Depletion from River",
"E" : "Evaporative",
"F" : "Federal Reserved",
"G" : "Geothermal",
"H" : "Household Use Only",
"K" : "Snow Making",
"M" : "Minimum Streamflow",
"N" : "Net Effect on River",
"P" : "Power Generation",
"Q" : "Other",
"R" : "Recharge",
"S" : "Export from State",
"T" : "Transmountain Export",
"W" : "Wildlife",
"X" : "All Beneficial Uses"}

def retrieveBenUse(colrowValue):
    if colrowValue == "" or pd.isnull(colrowValue):
        outString = ""
    else:
        String1 = str(colrowValue).strip()
        x=[]
        x[:] = String1
        try:
            outList = []
            for i in range(len(x)):
                y = x[i].strip()
                y = BenUseDict[y]
                outList.append(y)
            outString = ",".join(str(e) for e in outList)
        except:
            outString = ""
    return outString

dfinPOD['in_BeneficialUseCategory'] = dfinPOD.apply(lambda row: retrieveBenUse(row['Decreed Uses']), axis=1)
dfinPOD['in_BeneficialUseCategory'].unique()

array(['Irrigation,Municipal,Commercial,Recreation,Fishery,Domestic,Augmentation',
       'Irrigation,Municipal,Commercial,Domestic',
       'Commercial,Industrial,Domestic,Augmentation', ...,
       'Commercial,Recreation,Fishery,Fire,Other,Wildlife',
       'Irrigation,Stock,Evaporative,Wildlife',
       'Storage,Irrigation,Commercial,Domestic,Stock,Wildlife'],
      shape=(2754,), dtype=object)

In [7]:
#Determining WaterSourceTypeCV

WSTypeDict = {
"Aquifer NNT/NT Reservation" : "Surface Water",
"Ditch" : "Surface Water",
"Ditch System" : "Surface Water",
"Exchange Plan" : "Surface Water",
"Measuring Point" : "Surface Water",
"Mine" : "Surface Water",
"Minimum Flow" : "Surface Water",
"Other" : "Surface Water",
"Pipeline" : "Surface Water",
"Power Plant" : "Surface Water",
"Pump" : "Surface Water",
"Reach" : "Surface Water",
"Reach (Aggregating)" : "Surface Water",
"Recharge Area" : "Surface Water",
"Recharge Area Group" : "Surface Water",
"Reservoir" : "Surface Water",
"Reservoir System" : "Surface Water",
"Seep" : "Surface Water",
"Spring" : "Surface Water",
"Stream Gage" : "Surface Water",
"Well" : "Groundwater",
"Well Field" : "Groundwater",
"Well Group" : "Groundwater",
"Augmentation/Replacement Plan" : "Groundwater"}

def retrieveWaterSourceTypeCV(colrowValue):
    if (colrowValue == "") or (pd.isnull(colrowValue)):
        outString = "WaDE Blank"
    else:
        colrowValue = str(colrowValue).strip()
        try:
            outString = WSTypeDict[colrowValue]
        except:
            outString = "WaDE Blank"
    return outString

dfinPOD['in_WaterSourceTypeCV'] = dfinPOD.apply(lambda row: retrieveWaterSourceTypeCV(row['Structure Type']), axis=1)
dfinPOD['in_WaterSourceTypeCV'].value_counts()

in_WaterSourceTypeCV
Surface Water    96165
Groundwater      76947
WaDE Blank          16
Name: count, dtype: int64

In [8]:
# Allocation_CFS
# If Decreed Units = "C" and Net Absolute != 0, then return Net Absolute
# Elif Decreed Units = "C" and Net Conditional != 0, then return Net Conditional
# Else return blank

# For creating Allocation_CFS
def assignAllocation_CFS(valA, valB, valC):
    valA = str(valA).strip()
    if (valB != 0) and (valC != 0):
        outString = 0
    else:
        if (valA == "C") and (valB != 0):
            outString = valB
        elif (valA  == "C") and (valC != 0):
            outString = valC
        else:
            outString = 0
    return outString

dfinPOD['in_AllocationFlow_CFS'] = dfinPOD.apply(lambda row: assignAllocation_CFS(row["Decreed Units"], row["Net Absolute"], row["Net Conditional"]), axis=1)
dfinPOD['in_AllocationFlow_CFS'].unique()

array([ 0.   , 14.   ,  1.   , ...,  0.495, 28.25 ,  7.27 ], shape=(4642,))

In [9]:
# AllocationVolume_AF
# If Decreed Units = "A" and Net Absolute != 0, then return Net Absolute
# Elif Decreed Units = "A" and Net Conditional != 0, then return Net Conditional
# Else return blank

# For creating AllocationVolume_AF
def assignAllocationVolume_AF(valA, valB, valC):
    valA = str(valA).strip()
    if (valB != 0) and (valC != 0):
        outString = 0
    else:
        if (valA == "A") and (valB != 0):
            outString = valB
        elif (valA  == "A") and (valC != 0):
            outString = valC
        else:
            outString = 0
    return outString

dfinPOD['in_AllocationVolume_AF'] = dfinPOD.apply(lambda row: assignAllocationVolume_AF(row["Decreed Units"], row["Net Absolute"], row["Net Conditional"]), axis=1)
dfinPOD['in_AllocationVolume_AF'].unique()

array([62.   ,  0.   , 23.   , ...,  0.457,  6.132,  0.716], shape=(6139,))

In [10]:
# For creating AllocationLegalStatusCV
# If Net Absolute = 0 and Net Condontial = 0, then Condtional Aboslute
# Elif Net Absolute = 0 and Net Condontial != 0, then Condtional
# Else, Aboslute

def assignAllocationLegalStatusCV(valA, valB):
    if (valA == 0) and (valB == 0):
        outString = "Conditional Absolute"
    elif (valA == 0) and (valB != 0):
        outString = "Conditional"
    else:
        outString = "Absolute"
    return outString

dfinPOD['in_AllocationLegalStatusCV'] = dfinPOD.apply(lambda row: assignAllocationLegalStatusCV(row['Net Absolute'], row['Net Conditional']), axis=1)
dfinPOD['in_AllocationLegalStatusCV'].value_counts()

in_AllocationLegalStatusCV
Absolute                135321
Conditional Absolute     27885
Conditional               9922
Name: count, dtype: int64

In [11]:
# Need a unique identifier for WaDE AllocationNativeID.  Combine combine **Admin No**, **Order No**, **Decreed Units**, & **WDID** into single string entry.

# For creating AllocationAmount
def assignAllocationNativeID(colrowValueA, colrowValueB, colrowValueC, colrowValueD):
    colrowValueA = str(colrowValueA).strip()
    colrowValueB = str(colrowValueB).strip()
    colrowValueD = str(colrowValueD).strip()
    outString = "-".join(map(str, [colrowValueA, colrowValueB, colrowValueC, colrowValueD]))
    return outString

dfinPOD['in_AllocationNativeID'] = dfinPOD.apply(lambda row: assignAllocationNativeID(row['Admin No'], row['Order No'], row['Decreed Units'], row['WDID']), axis=1)
dfinPOD['in_AllocationNativeID'].unique()

array(['54296.0-0-A-5803688', '54296.0-0-C-5805086',
       '55882.55658-0-A-4303802', ..., '62091.54708-0-A-5403636',
       '63343.0-0-A-112518', '61726.0-0-A-5503621'],
      shape=(172979,), dtype=object)

In [12]:
# create output POD dataframe
df = pd.DataFrame()

# Data Assessment UUID
df['WaDEUUID'] = dfinPOD['WaDEUUID']

# Method Info
df['in_MethodUUID'] = "COwr_M1"

# Variable Info
df['in_VariableSpecificUUID'] = "COwr_V1" # for wr records portion only, will create sa portion below
df['in_AggregationIntervalUnitCV'] = "Annual"
df['in_VariableCV'] = "Allocation"

# Organization Info
df['in_OrganizationUUID'] = "COwr_O1"

# WaterSource Info
df['in_Geometry'] = ""
df['in_GNISFeatureNameCV'] = ""
df['in_WaterQualityIndicatorCV'] = "Fresh"
df['in_WaterSourceName'] = dfinPOD['Water Source']
df['in_WaterSourceNativeID'] = "" # auto fill in below
df['in_WaterSourceTypeCV'] = dfinPOD['in_WaterSourceTypeCV']

# Site Info
df['in_CoordinateAccuracy'] = ""
df['in_CoordinateMethodCV'] = dfinPOD['Location Accuracy']
df['in_County'] = dfinPOD['County']
df['in_EPSGCodeCV'] = 4326
df['in_Geometry'] = ""
df['in_GNISCodeCV'] = ""
df['in_HUC12'] = ""
df['in_HUC8'] = ""
df['in_Latitude'] = dfinPOD['Latitude']
df['in_Longitude'] = dfinPOD['Longitude']
df['in_NHDNetworkStatusCV'] = ""
df['in_NHDProductCV'] = ""
df['in_PODorPOUSite'] = "POD"
df['in_SiteName'] = dfinPOD['Structure Name']
df['in_SiteNativeID'] = dfinPOD['WDID'].replace("", 0).fillna(0).astype(int).astype(str)
df['in_SitePoint'] = ""
df['in_SiteTypeCV'] = dfinPOD['Structure Type'].astype(str)
df['in_StateCV'] = "CO"
df['in_USGSSiteID'] = ""

# AllocationAmount Info
df['in_AllocationApplicationDate'] = ""
df['in_AllocationAssociatedConsumptiveUseSiteIDs'] = ""
df['in_AllocationAssociatedWithdrawalSiteIDs'] = ""
df['in_AllocationBasisCV'] = ""
df['in_AllocationChangeApplicationIndicator'] = ""
df['in_AllocationCommunityWaterSupplySystem'] = ""
df['in_AllocationCropDutyAmount'] = ""
df['in_AllocationExpirationDate'] = ""
df['in_AllocationFlow_CFS'] = dfinPOD['in_AllocationFlow_CFS'].astype(float) # see above for conversion
df['in_AllocationLegalStatusCV'] = dfinPOD['in_AllocationLegalStatusCV']
df['in_AllocationNativeID'] =  dfinPOD['in_AllocationNativeID'].astype(str)
df['in_AllocationOwner'] = ""
df['in_AllocationPriorityDate'] = dfinPOD['Appropriation Date']
df['in_AllocationSDWISIdentifierCV'] = ""
df['in_AllocationTimeframeEnd'] = "12/31"
df['in_AllocationTimeframeStart'] = "01/01"
df['in_AllocationTypeCV'] = ""
df['in_AllocationVolume_AF'] = dfinPOD['in_AllocationVolume_AF'].astype(float) # see above for conversion
df['in_BeneficialUseCategory'] = dfinPOD['in_BeneficialUseCategory']
df['in_CommunityWaterSupplySystem'] = ""
df['in_CropTypeCV'] = ""
df['in_CustomerTypeCV'] = ""
df['in_DataPublicationDate'] = ""
df['in_DataPublicationDOI'] = ""
df['in_ExemptOfVolumeFlowPriority'] = 0 # 1 or 0, if we want this data excempt
df['in_GeneratedPowerCapacityMW'] = ""
df['in_IrrigatedAcreage'] = ""
df['in_IrrigationMethodCV'] = ""
df['in_LegacyAllocationIDs'] = ""
df['in_OwnerClassificationCV'] = ""
df['in_PopulationServed'] = ""
df['in_PowerType'] = ""
df['in_PrimaryBeneficialUseCategory'] = ""
df['in_SDWISIdentifierCV'] = ""
df['in_WaterAllocationNativeURL'] = dfinPOD['More Information']

outPOD = df.drop_duplicates().reset_index(drop=True)
print(len(outPOD))
outPOD.head()

173128

,WaDEUUID,in_MethodUUID,in_VariableSpecificUUID,in_AggregationIntervalUnitCV,in_VariableCV,in_OrganizationUUID,in_Geometry,in_GNISFeatureNameCV,in_WaterQualityIndicatorCV,in_WaterSourceName,in_WaterSourceNativeID,in_WaterSourceTypeCV,in_CoordinateAccuracy,in_CoordinateMethodCV,in_County,in_EPSGCodeCV,in_GNISCodeCV,in_HUC12,in_HUC8,in_Latitude,in_Longitude,in_NHDNetworkStatusCV,in_NHDProductCV,in_PODorPOUSite,in_SiteName,in_SiteNativeID,in_SitePoint,in_SiteTypeCV,in_StateCV,in_USGSSiteID,in_AllocationApplicationDate,in_AllocationAssociatedConsumptiveUseSiteIDs,in_AllocationAssociatedWithdrawalSiteIDs,in_AllocationBasisCV,in_AllocationChangeApplicationIndicator,in_AllocationCommunityWaterSupplySystem,in_AllocationCropDutyAmount,in_AllocationExpirationDate,in_AllocationFlow_CFS,in_AllocationLegalStatusCV,in_AllocationNativeID,in_AllocationOwner,in_AllocationPriorityDate,in_AllocationSDWISIdentifierCV,in_AllocationTimeframeEnd,in_AllocationTimeframeStart,in_AllocationTypeCV,in_AllocationVolume_AF,in_BeneficialUseCategory,in_CommunityWaterSupplySystem,in_CropTypeCV,in_CustomerTypeCV,in_DataPublicationDate,in_DataPublicationDOI,in_ExemptOfVolumeFlowPriority,in_GeneratedPowerCapacityMW,in_IrrigatedAcreage,in_IrrigationMethodCV,in_LegacyAllocationIDs,in_OwnerClassificationCV,in_PopulationServed,in_PowerType,in_PrimaryBeneficialUseCategory,in_SDWISIdentifierCV,in_WaterAllocationNativeURL
0,d0,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,YAMPA RIVER,,Surface Water,,Digitized,ROUTT,4326,,,,40.41105,-106.79897,,,POD,GOLF COURSE POND,5803688,,Reservoir,CO,,,,,,,,,,0.00000,Conditional,54296.0-0-A-5803688,,08/28/1998,,12/31,01/01,,62.00000,"Irrigation,Municipal,Commercial,Recreation,Fis...",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
1,d1,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,GROUNDWATER: YAMPA RIVER,,Groundwater,,GPS,ROUTT,4326,,,,40.41998,-106.81512,,,POD,CR WELL NO. 2,5805086,,Well,CO,,,,,,,,,,0.00000,Absolute,54296.0-0-C-5805086,,08/28/1998,,12/31,01/01,,0.00000,"Irrigation,Municipal,Commercial,Domestic",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
2,d2,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,CORRAL GULCH,,Surface Water,,Spotted from section lines,RIO BLANCO,4326,,,,39.91876,-108.49729,,,POD,CORRAL GULCH LOWER SITE RESERVOIR,4303802,,Reservoir,CO,,,,,,,,,,0.00000,Conditional,55882.55658-0-A-4303802,,05/21/2002,,12/31,01/01,,23.00000,"Commercial,Industrial,Domestic,Augmentation",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
3,d3,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,WALTON CREEK,,Surface Water,,GPS,ROUTT,4326,,,,40.40917,-106.79544,,,POD,ENTERPRISE DITCH,5800627,,Ditch,CO,,,,,,,,,,14.00000,Absolute,13795.0-0-C-5800627,,10/08/1887,,12/31,01/01,,0.00000,"Irrigation,All Beneficial Uses",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
4,d4,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,WALTON CREEK,,Surface Water,,GPS,ROUTT,4326,,,,40.40917,-106.79544,,,POD,ENTERPRISE DITCH,5800627,,Ditch,CO,,,,,,,,,,1.00000,Absolute,54296.0-0-C-5800627,,08/28/1998,,12/31,01/01,,0.00000,"Irrigation,Municipal,Commercial,Domestic",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...

## Place of Use Data

In [13]:
# # Input File
# inputFile = "RawInputData/shapefiles/{enter file name here}.zip"
# dfinPOU = gpd.read_file(inputFile).replace(np.nan, "")
# dfinPOU['geometry'] = dfinPOU['geometry'].to_crs(epsg=4326) # Realign Geometry Projection

# # WaDE UUID tracker for data assessment
# if 'WaDEUUID' not in dfinPOU:
#     dfinPOU['WaDEUUID'] = "u" + dfinPOU.index.astype(str)
#     dfinPOU.to_csv('RawInputData/{enter file name here}.zip', compression=dict(method='zip', archive_name='{enter file name here}.csv'), index=False)

# print(len(dfinPOU))
# dfinPOU.head()

In [14]:
# # create output POD dataframe
# df = pd.DataFrame()

# # Data Assessment UUID
# df['WaDEUUID'] = dfinPOU['WaDEUUID']

# # Method Info
# df['in_MethodUUID'] = ""

# # Variable Info
# df['in_VariableSpecificUUID'] = ""

# # Organization Info
# df['in_OrganizationUUID'] = ""

# # WaterSource Info
# df['in_Geometry'] = ""
# df['in_GNISFeatureNameCV'] = ""
# df['in_WaterQualityIndicatorCV'] = ""
# df['in_WaterSourceName'] = ""
# df['in_WaterSourceNativeID'] = "" # auto fill in below if not provdied
# df['in_WaterSourceTypeCV'] = ""

# # Site Info
# df['in_CoordinateAccuracy'] = ""
# df['in_CoordinateMethodCV'] = ""
# df['in_County'] = ""
# df['in_EPSGCodeCV'] = ""
# df['in_Geometry'] = ""
# df['in_GNISCodeCV'] = ""
# df['in_HUC12'] = ""
# df['in_HUC8'] = ""
# df['in_Latitude'] = ""
# df['in_Longitude'] = ""
# df['in_NHDNetworkStatusCV'] = ""
# df['in_NHDProductCV'] = ""
# df['in_PODorPOUSite'] = "POU"  # "Place of Use"
# df['in_SiteName'] = ""
# df['in_SiteNativeID'] = "POU" + ""
# df['in_SitePoint'] = ""
# df['in_SiteTypeCV'] = ""
# df['in_StateCV'] = ""
# df['in_USGSSiteID'] = ""

# # AllocationAmount Info
# df['in_AllocationApplicationDate'] = ""
# df['in_AllocationAssociatedConsumptiveUseSiteIDs'] = ""
# df['in_AllocationAssociatedWithdrawalSiteIDs'] = ""
# df['in_AllocationBasisCV'] = ""
# df['in_AllocationChangeApplicationIndicator'] = ""
# df['in_AllocationCommunityWaterSupplySystem'] = ""
# df['in_AllocationCropDutyAmount'] = ""
# df['in_AllocationExpirationDate'] = ""
# df['in_AllocationFlow_CFS'] = ""
# df['in_AllocationLegalStatusCV'] =""
# df['in_AllocationNativeID'] =  ""
# df['in_AllocationOwner'] = ""
# df['in_AllocationPriorityDate'] = ""
# df['in_AllocationSDWISIdentifierCV'] = ""
# df['in_AllocationTimeframeEnd'] = ""
# df['in_AllocationTimeframeStart'] = ""
# df['in_AllocationTypeCV'] = ""
# df['in_AllocationVolume_AF'] = ""
# df['in_BeneficialUseCategory'] = ""
# df['in_CommunityWaterSupplySystem'] = ""
# df['in_CropTypeCV'] = ""
# df['in_CustomerTypeCV'] = ""
# df['in_DataPublicationDate'] = ""
# df['in_DataPublicationDOI'] = ""
# df['in_ExemptOfVolumeFlowPriority'] = "" # either a 1 or 0
# df['in_GeneratedPowerCapacityMW'] = ""
# df['in_IrrigatedAcreage'] = ""
# df['in_IrrigationMethodCV'] = ""
# df['in_LegacyAllocationIDs'] = ""
# df['in_OwnerClassificationCV'] = ""
# df['in_PopulationServed'] = ""
# df['in_PowerType'] = ""
# df['in_PrimaryBeneficialUseCategory'] = ""
# df['in_SDWISIdentifierCV'] = ""
# df['in_WaterAllocationNativeURL'] = ""


# outPOU = df.copy()
# outPOU = outPOU.drop_duplicates().reset_index(drop=True)
# print(len(outPOU))
# outPOU.head()

## Concatenate POD and POU Data.  Make needed changes

In [15]:
# Concatenate dataframes
frames = [outPOD]  # list all out dataframes here
outdf = pd.concat(frames)
outdf = outdf.drop_duplicates().reset_index(drop=True).replace(np.nan, "")
print(len(outdf))

173128

## Clean Data / data types

In [16]:
# Clean name entries of spcial characters
def removeSpecialCharsFunc(Val):
    Val = str(Val)
    Val = re.sub("[$@&.;/\)(-]", "", Val).title().replace("  ", " ").strip().rstrip(',')
    return Val

<>:4: SyntaxWarning: invalid escape sequence '\)'
<>:4: SyntaxWarning: invalid escape sequence '\)'
C:\Users\rjame\AppData\Local\Temp\ipykernel_19300\1085762661.py:4: SyntaxWarning: invalid escape sequence '\)'
  Val = re.sub("[$@&.;/\)(-]", "", Val).title().replace("  ", " ").strip().rstrip(',')

In [17]:
outdf['in_WaterSourceName'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_WaterSourceName']), axis=1)
outdf['in_WaterSourceName'].unique()

array(['Yampa River', 'Groundwater: Yampa River', 'Corral Gulch', ...,
       'Cameron Creek', 'Rossman Gulch', 'Shaffers Crossing Creek'],
      shape=(3278,), dtype=object)

In [18]:
outdf['in_County'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_County']), axis=1)
outdf['in_County'].unique()

array(['Routt', 'Rio Blanco', 'Logan', 'Summit', 'Moffat', 'La Plata',
       'Grand', 'Lake', 'Jackson', 'Montrose', 'Gunnison', 'Mesa',
       'Ouray', 'San Miguel', 'Costilla', 'Eagle', 'Weld', 'Morgan',
       'Washington', 'Elbert', 'Arapahoe', 'Adams', 'El Paso', 'Larimer',
       'Douglas', 'Boulder', 'Jefferson', 'Denver', 'Broomfield',
       'Unknown', 'Lincoln', 'Clear Creek', 'Teller', 'Gilpin', '',
       'Chaffee', 'Pueblo', 'Custer', 'Huerfano', 'Otero', 'Mineral',
       'Saguache', 'Rio Grande', 'Alamosa', 'Conejos', 'Park', 'Fremont',
       'Pitkin', 'Bent', 'Crowley', 'Las Animas', 'Kiowa', 'Hinsdale',
       'San Juan', 'Archuleta', 'Phillips', 'Garfield', 'Montezuma',
       'Dolores', 'Baca', 'Prowers', 'Delta', 'Kit Carson', 'Yuma',
       'Cheyenne', 'Sedgwick'], dtype=object)

In [19]:
outdf['in_SiteName'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_SiteName']), axis=1)
outdf['in_SiteName'].unique()

array(['Golf Course Pond', 'Cr Well No 2',
       'Corral Gulch Lower Site Reservoir', ..., 'Wildlife Pit #3',
       'Younglund 23Cw3063 Parcel 2 Nt Ar Well Field',
       'Rafto Big Hole Pond #18'], shape=(125305,), dtype=object)

In [20]:
outdf['in_AllocationOwner'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_AllocationOwner']), axis=1)
outdf['in_AllocationOwner'].unique()

array([''], dtype=object)

In [21]:
# Ensure Empty String / remove string value of "nan"

def ensureEmptyString(val):
    val = str(val).strip()
    if val == "" or val == " " or val == "nan" or pd.isnull(val):
        outString = ""
    else:
        outString = val
    return outString

In [22]:
outdf['in_WaterSourceName'] = outdf.apply(lambda row: ensureEmptyString(row['in_WaterSourceName']), axis=1)
outdf['in_WaterSourceName'].unique()

array(['Yampa River', 'Groundwater: Yampa River', 'Corral Gulch', ...,
       'Cameron Creek', 'Rossman Gulch', 'Shaffers Crossing Creek'],
      shape=(3278,), dtype=object)

In [23]:
outdf['in_WaterSourceTypeCV'] = outdf.apply(lambda row: ensureEmptyString(row['in_WaterSourceTypeCV']), axis=1)
outdf['in_WaterSourceTypeCV'].unique()

array(['Surface Water', 'Groundwater', 'WaDE Blank'], dtype=object)

In [24]:
outdf['in_SiteTypeCV'] = outdf.apply(lambda row: ensureEmptyString(row['in_SiteTypeCV']), axis=1)
outdf['in_SiteTypeCV'].unique()

array(['Reservoir', 'Well', 'Ditch', 'Pipeline', 'Spring',
       'Recharge Area', 'Pump', 'Other', 'Well Field', 'Seep',
       'Minimum Flow', 'Reservoir System', 'Well Group', 'Reach', 'Mine',
       'Power Plant', 'Measuring Point', 'Augmentation/Replacement Plan',
       'Recharge Area Group', 'Stream Gage', 'Exchange Plan',
       'Reach (Aggregating)', 'Stream Confluence',
       'Aquifer NNT/NT Reservation'], dtype=object)

In [25]:
outdf['in_SiteName'] = outdf.apply(lambda row: ensureEmptyString(row['in_SiteName']), axis=1)
outdf['in_SiteName'].unique()

array(['Golf Course Pond', 'Cr Well No 2',
       'Corral Gulch Lower Site Reservoir', ..., 'Wildlife Pit #3',
       'Younglund 23Cw3063 Parcel 2 Nt Ar Well Field',
       'Rafto Big Hole Pond #18'], shape=(125305,), dtype=object)

In [26]:
outdf['in_AllocationOwner'] = outdf.apply(lambda row: ensureEmptyString(row['in_AllocationOwner']), axis=1)
outdf['in_AllocationOwner'].unique()

array([''], dtype=object)

In [27]:
outdf['in_BeneficialUseCategory'] = outdf.apply(lambda row: ensureEmptyString(row['in_BeneficialUseCategory']), axis=1)
uniqueList = list(set([i.strip() for i in ','.join(outdf['in_BeneficialUseCategory'].astype(str)).split(',')]))
uniqueList.sort()
uniqueList

['All Beneficial Uses',
 'Augmentation',
 'Commercial',
 'Cumulative Accretion to River',
 'Domestic',
 'Evaporative',
 'Export from Basin',
 'Export from State',
 'Federal Reserved',
 'Fire',
 'Fishery',
 'Geothermal',
 'Household Use Only',
 'Industrial',
 'Irrigation',
 'Minimum Streamflow',
 'Municipal',
 'Other',
 'Power Generation',
 'Recharge',
 'Recreation',
 'Snow Making',
 'Stock',
 'Storage',
 'Transmountain Export',
 'Wildlife']

In [28]:
# Ensure Latitude entry is either numireic or a 0
outdf['in_Latitude'] = pd.to_numeric(outdf['in_Latitude'], errors='coerce').replace(0,"").fillna("")
outdf['in_Latitude'].unique()

array([40.411047, 40.419983, 39.918762, ..., 40.818472, 40.871512,
       40.812922], shape=(106701,), dtype=object)

In [29]:
# Ensure Longitude entry is either numireic or a 0
outdf['in_Longitude'] = pd.to_numeric(outdf['in_Longitude'], errors='coerce').replace(0,"").fillna("")
outdf['in_Longitude'].unique()

array([-106.79897, -106.81512, -108.497287, ..., -106.205936, -106.868824,
       -107.871605], shape=(107195,), dtype=object)

In [30]:
# Changing datatype of Priority Date to date fields entry
outdf['in_AllocationPriorityDate'] = pd.to_datetime(outdf['in_AllocationPriorityDate'], errors = 'coerce')
outdf['in_AllocationPriorityDate'] = pd.to_datetime(outdf["in_AllocationPriorityDate"].dt.strftime('%m/%d/%Y'))
outdf['in_AllocationPriorityDate'].unique()

<DatetimeArray>
['1998-08-28 00:00:00', '2002-05-21 00:00:00', '1887-10-08 00:00:00',
 '1940-01-01 00:00:00', '1891-06-22 00:00:00', '1999-12-14 00:00:00',
 '1892-07-01 00:00:00', '2006-12-07 00:00:00', '1896-05-10 00:00:00',
 '1890-05-25 00:00:00',
 ...
 '2019-08-31 00:00:00', '1953-11-09 00:00:00', '1902-07-16 00:00:00',
 '1995-07-14 00:00:00', '1889-10-20 00:00:00', '2021-04-22 00:00:00',
 '2022-11-08 00:00:00', '2021-01-22 00:00:00', '1909-11-02 00:00:00',
 '1999-10-14 00:00:00']
Length: 25690, dtype: datetime64[ns]

In [31]:
# Ensure Flow entry is either numireic or a 0
outdf['in_AllocationFlow_CFS'] = pd.to_numeric(outdf['in_AllocationFlow_CFS'], errors='coerce').round(2).replace(0,"").fillna("")
outdf['in_AllocationFlow_CFS'].unique()

array(['', 14.0, 1.0, ..., 20.9, 28.25, 7.27], shape=(2200,), dtype=object)

In [32]:
# Ensure Volume entry is either numireic or a 0
outdf['in_AllocationVolume_AF'] = pd.to_numeric(outdf['in_AllocationVolume_AF'], errors='coerce').round(2).replace(0,"").fillna("")
outdf['in_AllocationVolume_AF'].unique()

array([62.0, '', 23.0, ..., 2.73, 10.68, 4.73],
      shape=(5504,), dtype=object)

In [33]:
# Ensure Irrigated Acreage entry is either numireic or a 0
outdf['in_IrrigatedAcreage'] = pd.to_numeric(outdf['in_IrrigatedAcreage'], errors='coerce').round(2).replace(0,"").fillna("")
outdf['in_IrrigatedAcreage'].unique()

array([''], dtype=object)

In [34]:
# Creating WaDE Custom water source native ID for easy water source identification
# use unique WaterSourceName and WaterSourceType values
# ----------------------------------------------------------------------------------------------------

# Create temp in_WaterSourceNativeID dataframe of unique water source.
def assignIdValueFunc(colRowValue):
    string1 = str(colRowValue)
    outstring = "wadeId" + string1
    return outstring

dfTempID = pd.DataFrame()
dfTempID['in_WaterSourceName'] = outdf['in_WaterSourceName'].astype(str).str.strip()
dfTempID['in_WaterSourceTypeCV'] = outdf['in_WaterSourceTypeCV'].astype(str).str.strip()
dfTempID = dfTempID.drop_duplicates()

dfTempCount = pd.DataFrame(index=dfTempID.index)
dfTempCount["Count"] = range(1, len(dfTempCount.index) + 1)
dfTempID['in_WaterSourceNativeID'] = dfTempCount.apply(lambda row: assignIdValueFunc(row['Count']), axis=1)
dfTempID['linkKey'] = dfTempID['in_WaterSourceName'].astype(str) + dfTempID['in_WaterSourceTypeCV'].astype(str)
IdDict = pd.Series(dfTempID.in_WaterSourceNativeID.values, index=dfTempID.linkKey.astype(str)).to_dict()
# ----------------------------------------------------------------------------------------------------

# Retreive WaDE Custom site native ID
def retrieveIdValueFunc(checkVal, valA, valB):
    checkVal = str(checkVal).strip()
    if checkVal == "":
        linkKeyVal = str(valA).strip() + str(valB).strip()
        outString = IdDict[linkKeyVal]
    else:
        outString = checkVal
    return outString

outdf['in_WaterSourceNativeID'] = outdf.apply(lambda row: retrieveIdValueFunc(row['in_WaterSourceNativeID'], 
                                                                              row['in_WaterSourceName'], row['in_WaterSourceTypeCV']), axis=1)
outdf['in_WaterSourceNativeID'].unique()

array(['wadeId1', 'wadeId2', 'wadeId3', ..., 'wadeId3300', 'wadeId3301',
       'wadeId3302'], shape=(3302,), dtype=object)

In [35]:
# Creating WaDE Custom site native ID for easy site identification
# use Unique Latitude, Longitude, SiteName and SiteTypeCV values
# ----------------------------------------------------------------------------------------------------

# Create temp in_SiteNativeID dataframe of unique water source.
def assignIdValueFunc(colRowValue):
    string1 = str(colRowValue)
    outstring = "wadeId" + string1
    return outstring

dfTempID = pd.DataFrame()
dfTempID['in_Latitude'] = outdf['in_Latitude'].astype(str).str.strip()
dfTempID['in_Longitude'] = outdf['in_Longitude'].astype(str).str.strip()
dfTempID['in_SiteName'] = outdf['in_SiteName'].astype(str).str.strip()
dfTempID['in_SiteTypeCV'] = outdf['in_SiteTypeCV'].astype(str).str.strip()
dfTempID = dfTempID.drop_duplicates()

dfTempCount = pd.DataFrame(index=dfTempID.index)
dfTempCount["Count"] = range(1, len(dfTempCount.index) + 1)
dfTempID['in_SiteNativeID'] = dfTempCount.apply(lambda row: assignIdValueFunc(row['Count']), axis=1)
dfTempID['linkKey'] = dfTempID['in_Latitude'].astype(str) + dfTempID['in_Longitude'].astype(str) + dfTempID['in_SiteName'].astype(str)+ dfTempID['in_SiteTypeCV'].astype(str)
IdDict = pd.Series(dfTempID.in_SiteNativeID.values, index=dfTempID.linkKey.astype(str)).to_dict()
# ----------------------------------------------------------------------------------------------------

# Retreive WaDE Custom site native ID
def retrieveIdValueFunc(checkVal, valA, valB, valC, valD):
    checkVal = str(checkVal).strip()
    if checkVal == "":
        linkKeyVal = str(valA).strip() + str(valB).strip() + str(valC).strip() + str(valD).strip()
        outString = IdDict[linkKeyVal]
    else:
        outString = checkVal
    return outString

outdf['in_SiteNativeID'] = outdf.apply(lambda row: retrieveIdValueFunc(row['in_SiteNativeID'], 
                                                                       row['in_Latitude'], row['in_Longitude'],
                                                                       row['in_SiteName'], row['in_SiteTypeCV']), axis=1)
outdf['in_SiteNativeID'].unique()

array(['5803688', '5805086', '4303802', ..., '5403636', '112518',
       '5503621'], shape=(132467,), dtype=object)

## Drop non-Active AllocationLegalStatusCV Water Rights
- For this {state name / organization}, we don't want water rights that are considered: {enter string entries here}

In [36]:
# drop non-active AllocationLegalStatusCV values specific to that state.

# drop the list
dropLegalStatusList = ["Conditional"] # enter string entries here

# drop rows from above list
outdf = outdf[outdf.in_AllocationLegalStatusCV.isin(dropLegalStatusList) == False].reset_index(drop=True)

print(len(outdf))
outdf['in_AllocationLegalStatusCV'].unique()

163206

array(['Absolute', 'Conditional Absolute'], dtype=object)

## Shapefile Data
- For attaching geometry to POU csv inputs.

In [37]:
# # # Input File / or use same input as above

# gdfin1 = outdf.copy()
# gdfin1 = gpd.GeoDataFrame(gdfin1, geometry=gdfin1['in_Geometry'], crs="EPSG:4326") # covert to geodataframe
# print(len(gdfin1))
# gdfin1.head()

In [38]:
# # plot shape info to map
# gdfin1.plot()

In [39]:
# # create output for Regulatory Area #1 dataframe
# df = pd.DataFrame()

# columnsList = ['in_SiteNativeID', 'geometry']
# goutdf1 = pd.DataFrame(columns=columnsList, index=gdfin1.index)

# goutdf1['in_SiteNativeID'] =  gdfin1["in_SiteNativeID"].astype(str)  #in_ReportingUnitNativeID needs to match source from above equivalent dataframe
# goutdf1['geometry'] = gdfin1['in_Geometry']
# goutdf1 = goutdf1.drop_duplicates().reset_index(drop=True)

# # drop geometery from outdf
# outdf = outdf.drop(['in_Geometry'], axis=1)


# print(len(goutdf1))
# goutdf1.head()

## Export Data

In [40]:
outdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163206 entries, 0 to 163205
Data columns (total 65 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   WaDEUUID                                      163206 non-null  object
 1   in_MethodUUID                                 163206 non-null  object
 2   in_VariableSpecificUUID                       163206 non-null  object
 3   in_AggregationIntervalUnitCV                  163206 non-null  object
 4   in_VariableCV                                 163206 non-null  object
 5   in_OrganizationUUID                           163206 non-null  object
 6   in_Geometry                                   163206 non-null  object
 7   in_GNISFeatureNameCV                          163206 non-null  object
 8   in_WaterQualityIndicatorCV                    163206 non-null  object
 9   in_WaterSourceName                            163206 non-null  object
 10  in_WaterSourceNativeID                        163206 non-null  object
 11  in_WaterSourceTypeCV                          163206 non-null  object
 12  in_CoordinateAccuracy                         163206 non-null  object
 13  in_CoordinateMethodCV                         163206 non-null  object
 14  in_County                                     163206 non-null  object
 15  in_EPSGCodeCV                                 163206 non-null  int64
 16  in_GNISCodeCV                                 163206 non-null  object
 17  in_HUC12                                      163206 non-null  object
 18  in_HUC8                                       163206 non-null  object
 19  in_Latitude                                   163206 non-null  object
 20  in_Longitude                                  163206 non-null  object
 21  in_NHDNetworkStatusCV                         163206 non-null  object
 22  in_NHDProductCV                               163206 non-null  object
 23  in_PODorPOUSite                               163206 non-null  object
 24  in_SiteName                                   163206 non-null  object
 25  in_SiteNativeID                               163206 non-null  object
 26  in_SitePoint                                  163206 non-null  object
 27  in_SiteTypeCV                                 163206 non-null  object
 28  in_StateCV                                    163206 non-null  object
 29  in_USGSSiteID                                 163206 non-null  object
 30  in_AllocationApplicationDate                  163206 non-null  object
 31  in_AllocationAssociatedConsumptiveUseSiteIDs  163206 non-null  object
 32  in_AllocationAssociatedWithdrawalSiteIDs      163206 non-null  object
 33  in_AllocationBasisCV                          163206 non-null  object
 34  in_AllocationChangeApplicationIndicator       163206 non-null  object
 35  in_AllocationCommunityWaterSupplySystem       163206 non-null  object
 36  in_AllocationCropDutyAmount                   163206 non-null  object
 37  in_AllocationExpirationDate                   163206 non-null  object
 38  in_AllocationFlow_CFS                         163206 non-null  object
 39  in_AllocationLegalStatusCV                    163206 non-null  object
 40  in_AllocationNativeID                         163206 non-null  object
 41  in_AllocationOwner                            163206 non-null  object
 42  in_AllocationPriorityDate                     163206 non-null  datetime64[ns]
 43  in_AllocationSDWISIdentifierCV                163206 non-null  object
 44  in_AllocationTimeframeEnd                     163206 non-null  object
 45  in_AllocationTimeframeStart                   163206 non-null  object
 46  in_AllocationTypeCV                           163206 non-null  object
 47  in_AllocationVolume_AF                        163206 non-null  object
 48  in_BeneficialUseCategory                      163206 non-null  object
 49  in_CommunityWaterSupplySystem                 163206 non-null  object
 50  in_CropTypeCV                                 163206 non-null  object
 51  in_CustomerTypeCV                             163206 non-null  object
 52  in_DataPublicationDate                        163206 non-null  object
 53  in_DataPublicationDOI                         163206 non-null  object
 54  in_ExemptOfVolumeFlowPriority                 163206 non-null  int64
 55  in_GeneratedPowerCapacityMW                   163206 non-null  object
 56  in_IrrigatedAcreage                           163206 non-null  object
 57  in_IrrigationMethodCV                         163206 non-null  object
 58  in_LegacyAllocationIDs                        163206 non-null  object
 59  in_OwnerClassificationCV                      163206 non-null  object
 60  in_PopulationServed                           163206 non-null  object
 61  in_PowerType                                  163206 non-null  object
 62  in_PrimaryBeneficialUseCategory               163206 non-null  object
 63  in_SDWISIdentifierCV                          163206 non-null  object
 64  in_WaterAllocationNativeURL                   163206 non-null  object
dtypes: datetime64[ns](1), int64(2), object(62)
memory usage: 80.9+ MB

In [41]:
outdf

,WaDEUUID,in_MethodUUID,in_VariableSpecificUUID,in_AggregationIntervalUnitCV,in_VariableCV,in_OrganizationUUID,in_Geometry,in_GNISFeatureNameCV,in_WaterQualityIndicatorCV,in_WaterSourceName,in_WaterSourceNativeID,in_WaterSourceTypeCV,in_CoordinateAccuracy,in_CoordinateMethodCV,in_County,in_EPSGCodeCV,in_GNISCodeCV,in_HUC12,in_HUC8,in_Latitude,in_Longitude,in_NHDNetworkStatusCV,in_NHDProductCV,in_PODorPOUSite,in_SiteName,in_SiteNativeID,in_SitePoint,in_SiteTypeCV,in_StateCV,in_USGSSiteID,in_AllocationApplicationDate,in_AllocationAssociatedConsumptiveUseSiteIDs,in_AllocationAssociatedWithdrawalSiteIDs,in_AllocationBasisCV,in_AllocationChangeApplicationIndicator,in_AllocationCommunityWaterSupplySystem,in_AllocationCropDutyAmount,in_AllocationExpirationDate,in_AllocationFlow_CFS,in_AllocationLegalStatusCV,in_AllocationNativeID,in_AllocationOwner,in_AllocationPriorityDate,in_AllocationSDWISIdentifierCV,in_AllocationTimeframeEnd,in_AllocationTimeframeStart,in_AllocationTypeCV,in_AllocationVolume_AF,in_BeneficialUseCategory,in_CommunityWaterSupplySystem,in_CropTypeCV,in_CustomerTypeCV,in_DataPublicationDate,in_DataPublicationDOI,in_ExemptOfVolumeFlowPriority,in_GeneratedPowerCapacityMW,in_IrrigatedAcreage,in_IrrigationMethodCV,in_LegacyAllocationIDs,in_OwnerClassificationCV,in_PopulationServed,in_PowerType,in_PrimaryBeneficialUseCategory,in_SDWISIdentifierCV,in_WaterAllocationNativeURL
0,d1,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Groundwater: Yampa River,wadeId2,Groundwater,,GPS,Routt,4326,,,,40.41998,-106.81512,,,POD,Cr Well No 2,5805086,,Well,CO,,,,,,,,,,,Absolute,54296.0-0-C-5805086,,1998-08-28,,12/31,01/01,,,"Irrigation,Municipal,Commercial,Domestic",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
1,d3,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Walton Creek,wadeId4,Surface Water,,GPS,Routt,4326,,,,40.40917,-106.79544,,,POD,Enterprise Ditch,5800627,,Ditch,CO,,,,,,,,,,14.00000,Absolute,13795.0-0-C-5800627,,1887-10-08,,12/31,01/01,,,"Irrigation,All Beneficial Uses",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
2,d4,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Walton Creek,wadeId4,Surface Water,,GPS,Routt,4326,,,,40.40917,-106.79544,,,POD,Enterprise Ditch,5800627,,Ditch,CO,,,,,,,,,,1.00000,Absolute,54296.0-0-C-5800627,,1998-08-28,,12/31,01/01,,,"Irrigation,Municipal,Commercial,Domestic",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
3,d6,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Springdale Creek,wadeId5,Surface Water,,Spotted from quarters,Logan,4326,,,,40.68422,-103.25241,,,POD,Springdale Cr Divr 2,6400688,,Ditch,CO,,,,,,,,,,3.00000,Absolute,56247.32872-0-C-6400688,,1940-01-01,,12/31,01/01,,,Storage,,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
4,d7,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Walton Creek,wadeId4,Surface Water,,GPS,Routt,4326,,,,40.40917,-106.79544,,,POD,Enterprise Ditch,5800627,,Ditch,CO,,,,,,,,,,,Conditional Absolute,15148.0-0-C-5800627,,1891-06-22,,12/31,01/01,,,Irrigation,,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163201,d173122,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Miller Creek,wadeId952,Surface Water,,GPS,Rio Blanco,4326,,,,39.91052,-107.77779,,,POD,Frank Smith Ditch,4300647,,Ditch,CO,,,,,,,,,,1.15000,Absolute,32172.22737-0-C-4300647,,1912-04-02,,12/31,01/01,,,Irrigation,,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
163202,d173123,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Blue River,wadeId1128,Surface Water,,Digitized,Summit,4326,,,,39.61031,-106.08932,,,POD,Silverthorne 2016 Effluent Exchange,3609145,,Reach,CO,,,,,,,,,,,Conditional Absolute,60434.0-0-C-3609145,,2015-06-18,,12/31,01/01,,,"Municipal,Augmentation",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
163203,d173124,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Coon Creek,wadeId379,Surface Water,,GPS,Jackson,4326,,,,40.81847,-106.20594,,,POD,Dulaney Ditch,4700598,,Ditch,CO,,,,,,,,,,2.50000,Absolute,14426.0-0-C-4700598,,1889-06-30,,12/31,01/01,,,Irrigation,,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
163204,d173125,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Silver City Creek,wadeId2488,Surface Water,,Per Decree,Routt,4326,,,,40.87151,-106.86882,,,POD,Wildlife Pit #3,5403636,,Reservoir,CO,,,,,,,,,,,Absolute,62091.54708-0-A-5403636,,1999-10-14,,12/31,01/01,,,"Stock,Wildlife",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...
163205,d173126,COwr_M1,COwr_V1,Annual,Allocation,COwr_O1,,,Fresh,Groundwater: Arapahoe,wadeId99,Groundwater,,Digitized,Elbert,4326,,,,39.45658,-104.51967,,,POD,Younglund 23Cw3063 Parcel 2 Nt Ar Well Field,112518,,Well Field,CO,,,,,,,,,,,Absolute,63343.0-0-A-112518,,2023-06-05,,12/31,01/01,,109.00000,"Storage,Irrigation,Commercial,Industrial,Fishe...",,,,,,0,,,,,,,,,,https://dwr.state.co.us/Tools/WaterRights/NetA...

In [42]:
# Export the output dataframe
outdf.to_csv('RawInputData/Pwr_Main.zip', compression=dict(method='zip', archive_name='Pwr_Main.csv'), index=False)  # The output, save as a zip
#goutdf1.to_csv('RawInputData/P_Geometry.zip', compression=dict(method='zip', archive_name='P_Geometry.csv'), index=False)  # The output geometry.