# Pre-processing Water Right and Time Series Water Use data for WaDE Upload
- Purpose:  To pre-process the data into one main file for simple DataFrame creation and extraction

In [1]:
# Needed Libraries / Modules

# ---- working with data ----
import os  # native operating system interaction
import numpy as np  # mathematical array manipulation
import pandas as pd  # data structure and data analysis
import geopandas as gpd  # geo-data structure and data analysis

# ---- visualization ----
import matplotlib.pyplot as plt  # plotting library
import seaborn as sns  # plotting library

# ---- API data retrieval ----
import requests  # http requests
import json  # JSON parse

# ---- Cleanup ----
import re  # string regular expression manipulation
from datetime import datetime  # date and time manipulation
pd.set_option('display.max_columns', 999)  # How to display all columns of a Pandas DataFrame in Jupyter Notebook
pd.set_option('display.float_format', lambda x: '%.5f' % x)  # suppress scientific notation in Pandas

In [2]:
# ---- working directory ----
workingDirString = "G:/Shared drives/WaDE Data/WaDE Data Folder/California/WaterAllocation_WaterUse_CSWRCB" # set working directory folder string here
os.chdir(workingDirString)
print(f'The working Directory is:', workingDirString)

The working Directory is: G:/Shared drives/WaDE Data/WaDE Data Folder/California/WaterAllocation_WaterUse_CSWRCB

## Data Input

In [3]:
# Input File #1 - ewrims_flat_file_pod
fileInput = "RawInputData/water_right/ewrims_flat_file_pod-flat-file.zip"
dfin1 = pd.read_csv(fileInput).replace(np.nan, "")

# WaDE UUID tracker for data assessment
if 'WaDEUUID' not in dfin1:
    dfin1['WaDEUUID'] = "in1" + dfin1.index.astype(str)
    dfin1.to_csv("RawInputData/water_right/ewrims_flat_file_pod-flat-file.zip", compression=dict(method='zip', archive_name='ewrims_flat_file_pod-flat-file.csv'), index=False)

print(len(dfin1))
dfin1.head()

C:\Users\rjame\AppData\Local\Temp\ipykernel_2832\259936738.py:3: DtypeWarning: Columns (13,49,59,61,66,72,74,88,89,91,94,96,98,99,103,105,110,121,126,132,133,146,147,148,150,153,154,155,156,157,158,159,160,161,162,163,166,167,168,169) have mixed types. Specify dtype option on import or set low_memory=False.
  dfin1 = pd.read_csv(fileInput).replace(np.nan, "")

67209

,ï»¿POD_ID,POD_NUMBER,POD_STATUS,SOURCE_TYPE,POD_NAME,POD_TYPE,DIVERSION_WORKS_STATUS,STREAM_CLASSIFICATION,DIRECT_DIV_AMOUNT,DIRECT_DIVERSION_RATE,DIRECT_DIV_RATE_UNIT,STORAGE_AMOUNT,DIVERSION_RATE_TO_OFF_STREAM,OFF_STO_DIV_RATE_UNIT,POD_LAST_UPDATE_DATE,POD_COUNT,APPL_ID,OBJECTID,POD_NUMBER_GIS,HAS_OPOD,APPL_POD,POD_ID_GIS,COUNTY,PARCEL_NUMBER,SP_ZONE,DIVERSION_SITE_NAME,NORTH_COORD,EAST_COORD,LATITUDE,LONGITUDE,QUARTER_QUARTER,QUARTER,SECTION_CLASSIFIER,SECTION_NUMBER,TOWNSHIP_NUMBER,TOWNSHIP_DIRECTION,RANGE_NUMBER,RANGE_DIRECTION,MERIDIAN,LOCATION_METHOD,SPECIAL_USE_AREA,SOURCE_NAME,TRIB_DESC,WATERSHED,HUC_12_NUMBER,HUC_12_NAME,HUC_8_NUMBER,HUC_8_NAME,QUAD_MAP_NAME,QUAD_MAP_NUMBER,WR_WATER_RIGHT_ID,APPLICATION_NUMBER,CERTIFICATE_ID,PERMIT_ID,LICENSE_ID,WATER_RIGHT_TYPE,WATER_RIGHT_STATUS,APPLICATION_NUMBER_PARTY,PWSS_ID,PRIORITY_DATE,RECEIPT_DATE,REJECTION_DATE,APPLICATION_RECD_DATE,APPLICATION_ACCEPTANCE_DATE,PROJECT_TYPE,RECORD_SUMMARY,INCOMPLETE_STATEMENT,NUMBER_OF_PROTESTS,AGENT_NAME,AGENT_ENTITY_TYPE,APPLICATION_PRIMARY_OWNER,PRIMARY_OWNER_ENTITY_TYPE,SUB_TYPE,INI_REPORTED_DIV_AMOUNT,INI_REPORTED_DIV_UNIT,FACE_VALUE_AMOUNT,FACE_VALUE_UNITS,FEE_DUE,FEE_RECEIVED,APPL_FEE_AMOUNT,APPL_FEE_AMT_RECD,MAX_DD_APPL,MAX_DD_UNITS,MAX_DD_ANN,MAX_STORAGE,MAX_TAKEN_FROM_SOURCE,YEAR_DIVERSION_COMMENCED,MAX_BENEFICIALLY_USED,SUPPLEMENTAL_STATEMENT_CYCLE,TYPE_OF_DIVERSION_FACILITY,QUANTITY_OF_WATER_DIVERTED,QOW_DIVERTED_UNIT,QUANTITY_MEASUREMENT_YEAR,MAX_RATE_OF_DIVERSION,MAX_RATE_OF_DIV_UNIT,RECENT_WATER_USE_MIN,WATER_USE_MIN_UNIT,RECENT_WATER_USE_MAX,WATER_USE_MAX_UNIT,REQUEST_FOR_REVOCATION_RECD,NUM_COMMENTS,NUM_ATTACHMENTS,LAST_UPDATE_DATE,STATE_WELL_NUMBER,DRILLED_WELL_YEAR,SURFACE_WATER_DIVERSIONS,DEPTH_OF_WELL,RELATIONSHIP_TYPE,PARTY_ID,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,PRIMARY_OWNER_NAME,PRIMARY_OWNER_ENTITY_TYPE_P,OFFICIAL_MAIL_RECEIVER,COUNT_NPO_OR_OTHER,CURRENT_STATUS,EFFECTIVE_DATE,UPDATE_DATETIME,USE_CODE,USE_STATUS,NUMBER_OF_RESIDENCES,SEPERATELY_OWNED,USE_POPULATION,USE_POPULATION_PEOPLE,ESTIMATED_USE_PER_PERSON,USE_POPULATION_STOCK,TYPE_OF_STOCK,AREA_FOR_INCI_IRRIGATION,USE_NET_ACREAGE,USE_GROSS_ACREAGE,USE_DIRECT_DIV_ANNUAL_AMOUNT,USE_DIRECT_DIVERSION_RATE,USE_DIRECT_DIV_RATE_UNITS,POU_DEVELOPMENT_STATUS,DIRECT_DIV_SEASON_START,DIRECT_DIV_SEASON_END,USE_STORAGE_AMOUNT,STORAGE_SEASON_START,STORAGE_SEASON_END,SEASON_DIRECT_DIV_RATE,SEASON_STORAGE_AMOUNT,SEASON_DIRECT_DIV_AA,DIRECT_DIV_SEASON_STATUS,COLLECTION_SEASON_STATUS,USE_COUNT,PERMIT_PERMIT_ID,PERMIT_ORIGINAL_ISSUE_DATE,COMPLETE_CONSTRUCTION_DATE,COMPLETE_APPLIC_WATER_DATE,LICENSE_LICENSE_ID,LICENSE_ORIGINAL_ISSUE_DATE,WATER_RIGHT_DESCRIPTION,PROGRAM_UNIT,LICENSE_REQUEST_TYPE,LICENSE_REQUESTED_DATE,INSPECTION_DATE,REPORT_DATE,OFFER_SENT_DATE,ACCEPTED_OFFER_DATE,PETITION_ID,PETITION_TYPE,PETITION_STATUS_TYPE,DATE_RECEIVED,DATE_COMPLETED,PET_LAST_UPDATE_DATE,NUM_OF_PETITIONS,ENF_CASE_NUMBER,ENF_CASE_START_DATE,ENF_CASE_CLOSURE_DATE,ENF_CASE_COUNTY,NUMBER_OF_ENFORCEMENT_CASE,WaDEUUID
0,60497,1.00000,Inactive,Surface,COMPOUND STOCK POND,Point of Direct Diversion,Existing,Unknown,48.00000,0.15000,Cubic Feet per Second,,,,,2,T032025,97404.00000,1.00000,N,T032025_01,60497,San Diego,,6.00000,COMPOUND STOCK POND,1814680.00000,6549776.00000,32.64560,-116.28860,NE,SW,,32.00000,17.00000,S,7.00000,E,San Bernardino,GIS_NE,,UNNAMED STREAM,BOUNDARY CREEK,ANZA BORREGO,181002020203.00000,Boundary Creek,18100202.00000,Carrizo Creek,LIVE OAK SPRINGS,,1,T032025,,,,Temporary Permit,Cancelled,T032025,,,4/18/2013,,4/18/2013,4/18/2013,,Migrated data from old WRIMS system.,,0,,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,,,,48.00000,Acre-feet per Year,1570.00000,1570.00000,1570.00000,1570.00000,0.15000,Cubic Feet per Second,48.00000,,0.00000,,0.00000,,,,,,,,,,,,N,1,1,,,,,0.00000,Primary Owner,539608.00000,4/18/2013,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,Y,0,Cancelled,8/9/2013,,Dust Control,Requested when filed,,,0.00000,,,,,,0.00000,0.00000,109.00000,0.15000,Cubic Feet per Second,Partial,1/1,12/31,0.00000,,,0.15000,0.00000,109.00000,Requested when filed,,1,,,,,,,,,,,,,,,,,,,,,,,,,,0,in10
1,60498,2.00000,Inactive,Surface,LAKE DOMINGO,Point of Direct Diversion,Proposed,Unknown,48.00000,0.15000,Cubic Feet per Second,,,,,2,T032025,95308.00000,2.00000,N,T032025_02,60498,San Diego,,6.00000,LAKE DOMINGO,1803326.00000,6554711.00000,32.61440,-116.27260,SE,SW,,9.00000,18.00000,S,7.00000,E,San Bernardino,GIS_NE,,LAKE DOMINGO,BOUNDARY CREEK,ANZA BORREGO,181002020203.00000,Boundary Creek,18100202.00000,Carrizo Creek,TIERRA DEL SOL,,1,T032025,,,,Temporary Permit,Cancelled,T032025,,,4/18/2013,,4/18/2013,4/18/2013,,Migrated data from old WRIMS system.,,0,,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,,,,48.00000,Acre-feet per Year,1570.00000,1570.00000,1570.00000,1570.00000,0.15000,Cubic Feet per Second,48.00000,,0.00000,,0.00000,,,,,,,,,,,,N,1,1,,,,,0.00000,Primary Owner,539608.00000,4/18/2013,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,Y,0,Cancelled,8/9/2013,,Dust Control,Requested when filed,,,0.00000,,,,,,0.00000,0.00000,109.00000,0.15000,Cubic Feet per Second,Partial,1/1,12/31,0.00000,,,0.15000,0.00000,109.00000,Requested when filed,,1,,,,,,,,,,,,,,,,,,,,,,,,,,0,in11
2,404,1.00000,Active,,,Point of Direct Diversion,,,0.00000,0.02500,Cubic Feet per Second,0.00000,,,,4,A000016,58413.00000,1.00000,N,A000016_01,404,Los Angeles,,5.00000,,2032842.89063,6474612.14777,34.57797,-118.28921,NE,SE,,30.00000,6.00000,N,13.00000,W,San Bernardino,DD_NE,,ICY SPRING NO 1,,ANTELOPE,180902061401.00000,Headwaters Amargosa Creek,18090206.00000,Antelope-Fremont Valleys,SLEEPY VALLEY,OO071,2,A000016,41.00000,30.00000,41.00000,Appropriative,Licensed,A000016,,,,,,2/15/1915,,Migrated data from old WRIMS system.,,0,,,JUAN SERVIANO GARCIA LOPEZ,Individual,,,,18.10000,Acre-feet per Year,10.00000,10.00000,10.00000,10.00000,0.02500,Cubic Feet per Second,0.00000,0.00000,18.10000,,0.00000,,,,,,,,,,,,N,0,2,,,,,,Primary Owner,650859.00000,4/9/2025,,JUAN GARCIA LOPEZ,Individual,Y,3,Licensed,2/19/1915,,Domestic,Migrated from old WRIMS data,,,0.00000,,,,,,0.00000,0.00000,0.00000,0.00000,,,1/1,12/31,0.00000,,,,0.00000,,Migrated from old WRIMS data,Migrated from old WRIMS data,2,30.00000,10/28/1915,,,41.00000,9/25/1918,Migrated data from old WRIMS system.,,Permitee Request,,,,,,,,,,,,,,,,,0,in12
3,17603,1.00000,Active,,,Point of Direct Diversion,,,0.00000,0.02500,Cubic Feet per Second,0.00000,,,,4,A000016,58414.00000,1.00000,N,A000016_01,17603,Los Angeles,,5.00000,,2032842.89063,6474612.14777,34.57797,-118.28921,NE,SE,,30.00000,6.00000,N,13.00000,W,San Bernardino,DD_NE,,KERR SPRING NO 2,,ANTELOPE,180902061401.00000,Headwaters Amargosa Creek,18090206.00000,Antelope-Fremont Valleys,SLEEPY VALLEY,OO071,2,A000016,41.00000,30.00000,41.00000,Appropriative,Licensed,A000016,,,,,,2/15/1915,,Migrated data from old WRIMS system.,,0,,,JUAN SERVIANO GARCIA LOPEZ,Individual,,,,18.10000,Acre-feet per Year,10.00000,10.00000,10.00000,10.00000,0.02500,Cubic Feet per Second,0.00000,0.00000,18.10000,,0.00000,,,,,,,,,,,,N,0,2,,,,,,Primary Owner,650859.00000,4/9/2025,,JUAN GARCIA LOPEZ,Individual,Y,3,Licensed,2/19/1915,,Domestic,Migrated from old WRIMS data,,,0.00000,,,,,,0.00000,0.00000,0.00000,0.00000,,,1/1,12/31,0.00000,,,,0.00000,,Migrated from old WRIMS data,Migrated from old WRIMS data,2,30.00000,10/28/1915,,,41.00000,9/25/1918,Migrated data from old WRIMS system.,,Permitee Request,,,,,,,,,,,,,,,,,0,in13
4,29028,1.00000,Active,,,Point of Direct Diversion,,,0.00000,0.02500,Cubic Feet per Second,0.00000,,,,4,A000016,57787.00000,1.00000,N,A000016_01,29028,Los Angeles,005-370-43-00,5.00000,,2033642.80241,6474614.80623,34.58017,-118.28921,SE,NE,,30.00000,6.00000,N,13.00000,W,San Bernardino,DD_NE,,KERR SPRING NO 1,,ANTELOPE,180902061401.00000,Headwaters Amargosa Creek,18090206.00000,Antelope-Fremont Valleys,SLEEPY VALLEY,OO071,2,A000016,41.00000,30.00000,41.00000,Appropriative,Licensed,A000016,,,,,,2/15/1915,,Migrated data from old WRIMS system.,,0,,,JUAN SERVIANO GARCIA LOPEZ,Individual,,,,18.10000,Acre-feet per Year,10.00000,10.00000,10.00000,10.00000,0.02500,Cubic Feet per Second,0.00000,0.00000,18.10000,,0.00000,,,,,,,,,,,,N,0,2,,,,,,Primary Owner,650859.00000,4/9/2025,,JUAN GARCIA LOPEZ,Individual,Y,3,Licensed,2/19/1915,,Domestic,Migrated from old WRIMS data,,,0.00000,,,,,,0.00000,0.00000,0.00000,0.00000,,,1/1,12/31,0.00000,,,,0.00000,,Migrated from old WRIMS data,Migrated from old WRIMS data,2,30.00000,10/28/1915,,,41.00000,9/25/1918,Migrated data from old WRIMS system.,,Permitee Request,,,,,,,,,,,,,,,,,0,in14

In [4]:
# Input File #2 - water-rights-water-use-reported-short
fileInput = "RawInputData/water_use/621c31ae-7ea0-4915-b7dc-dfcb7efc77b9.zip"
dfin2 = pd.read_csv(fileInput).replace(np.nan, "")

# WaDE UUID tracker for data assessment
if 'WaDEUUID' not in dfin2:
    dfin2['WaDEUUID'] = "in2" + dfin2.index.astype(str)
    dfin2.to_csv("RawInputData/water_use/621c31ae-7ea0-4915-b7dc-dfcb7efc77b9.zip", compression=dict(method='zip', archive_name='621c31ae-7ea0-4915-b7dc-dfcb7efc77b9.csv'), index=False)

print(len(dfin2))
dfin2.head()

3296000

,ï»¿_id,MONTH NAME,MONTH FORMATTED,WATER_RIGHT_ID,APPL_ID,YEAR,MONTH,AMOUNT,DIVERSION_TYPE,WaDEUUID
0,1,May,5/1/2017,144,A001020,2017,5,0.00000,DIRECT,in20
1,2,May,5/1/2017,144,A001020,2017,5,0.00000,STORAGE,in21
2,3,June,6/1/2017,144,A001020,2017,6,0.00000,DIRECT,in22
3,4,June,6/1/2017,144,A001020,2017,6,0.00000,STORAGE,in23
4,5,June,6/1/2017,144,A001020,2017,6,0.00000,USE,in24

In [5]:
# issue of too many comma separated values.  Will leave blank or now

# #POD_TYPE fix
# # we only want the first listed POD_TYPE value

# def firstPOD_TYPEFunc(val):
#     val = str(val).strip()
#     if "," in val:
#         outString = val.split(",")
#         # outString = val[0]
#         outString = ''.join(outString)
#     else:
#         outString = val
#     return outString

# dfin1['POD_TYPE'] = dfin1.apply(lambda row: firstPOD_TYPEFunc(row['POD_TYPE']), axis=1)
# dfin1['POD_TYPE'].value_counts()

In [6]:
# Clean data a little

dfin1 = dfin1.fillna("") # remove nan values
dfin1['USE_DIRECT_DIVERSION_RATE'] = pd.to_numeric(dfin1['USE_DIRECT_DIVERSION_RATE'], errors='coerce').fillna(0) # make sure this is numeric.

In [7]:
# WaterSoureTypeCV fix
# some SOURCE_TYPE are blank, but SOURCE_TYPE is blank for not all those that share a similar SOURCE_NAME

dfTempW = dfin1[['SOURCE_NAME', 'SOURCE_TYPE']].copy()
dfTempW['SOURCE_NAME'] = dfTempW['SOURCE_NAME'].astype(str).str.strip()
dfTempW['SOURCE_TYPE'] = dfTempW['SOURCE_TYPE'].astype(str).str.strip()
dfTempW = dfTempW.drop_duplicates()
dfTempW = dfTempW[dfTempW['SOURCE_TYPE'] != ""]
wDict = pd.Series(dfTempW.SOURCE_TYPE.values, index=dfTempW.SOURCE_NAME.astype(str)).to_dict()

# Retreive WaDE Custom site native ID
def fillinWaterSourceTypeWithNameFunc(valName, valType):
    valName = str(valName).strip()
    valType = str(valType).strip()
    if valType == "":
        try:
            outString = wDict[valName]
        except:
            outString = "WaDE Blank"
    else:
        outString = valType
    return outString

dfin1['in_WaterSourceTypeCV'] = dfin1.apply(lambda row: fillinWaterSourceTypeWithNameFunc(row['SOURCE_NAME'], row['SOURCE_TYPE']), axis=1)
dfin1['in_WaterSourceTypeCV'].value_counts()

in_WaterSourceTypeCV
Surface       36349
Subsurface    20052
WaDE Blank    10808
Name: count, dtype: int64

In [8]:
# Create VariableSpecificCv value
def createVariableSpecificUUID(unit):
    outString = ""
    if unit == "Cubic Feet per Second":
        outString = "CSWRCBwrwu_V1"
    if unit == "Gallons per Day":
        outString = "CSWRCBwrwu_V1"
    if unit == "Acre-feet per Year":
        outString = "CSWRCBwrwu_V1"
    if unit == "Gallons per Minute":
        outString = "CSWRCBwrwu_V1"
    if unit == 'Acre-feet':
        outString = "CSWRCBwrwu_V2"
    if unit == 'Gallons':
        outString = "CSWRCBwrwu_V2"
    else:
        outString = "CSWRCBwrwu_V1"

    return(outString)

dfin1['in_VariableSpecificUUID'] = dfin1.apply(lambda row: createVariableSpecificUUID(row['USE_DIRECT_DIV_RATE_UNITS']), axis=1)
dfin1['in_VariableSpecificUUID'].unique()

array(['CSWRCBwrwu_V1', 'CSWRCBwrwu_V2'], dtype=object)

In [9]:
# convert all flow values to CFS

def convertFlowFunc(val, unit):
    CFS_Value = None
    if unit == "Cubic Feet per Second":
        CFS_Value = val
    if unit == "Gallons per Day":
        CFS_Value = val / (646316.883)
    if unit == "Acre-feet per Year":
        CFS_Value = val / (723.968)
    if unit == "Gallons per Minute":
        CFS_Value = val / (448.83117)
    return(CFS_Value)

dfin1['in_AllocationFlow_CFS'] = dfin1.apply(lambda row: convertFlowFunc(row['USE_DIRECT_DIVERSION_RATE'], row['USE_DIRECT_DIV_RATE_UNITS']), axis=1)
dfin1['in_AllocationFlow_CFS'].unique()

array([1.50000000e-01,            nan, 3.73000000e+02, ...,
       5.92650461e-01, 6.90682869e+00, 2.66000000e+02], shape=(1591,))

In [10]:
# convert all volume values to AF

def convertVolumeFunc(val, unit):
    AF_Value = None
    if unit == 'Acre-feet':
        AF_Value = val
    if unit == 'Gallons':
        AF_Value = val / (325850.943)
    return(AF_Value)

dfin1['in_AllocationVolume_AF'] = dfin1.apply(lambda row: convertVolumeFunc(row['USE_DIRECT_DIVERSION_RATE'], row['USE_DIRECT_DIV_RATE_UNITS']), axis=1)
dfin1['in_AllocationVolume_AF'].unique()

array([      nan, 0.000e+00, 1.300e-01, 3.650e+02, 2.062e+01])

In [11]:
# remove speicial characters from SUB_TYPE

def cleanupSubTypeFunc(val):
    val = str(val).strip()
    val = val.rstrip('_') # remove trailing "_"
    val = val.rstrip(',') # remove trailing commas
    if val == "" or val == "nan" or pd.isnull(val):
        outString = ""
    else:
        val = val.replace("," ," ")
        outString = "" + val
    return outString

dfin1['wade_SUB_TYPE'] = dfin1.apply(lambda row: cleanupSubTypeFunc(row['SUB_TYPE']), axis=1)
dfin1['wade_SUB_TYPE'].unique()

array(['', 'RIPARIAN', 'RIPARIAN PRE1914', 'PRE1914', 'OTHER',
       'PRE1914 OTHER', 'COURTADJ', 'RIPARIAN PRE1914 OTHER',
       'RIPARIAN PRE1914 COURTADJ OTHER', 'RIPARIAN PRE1914 COURTADJ',
       'PRE1914 COURTADJ', 'RIPARIAN OTHER', 'RIPARIAN COURTADJ',
       'PRE1914 PENDING', 'PENDING', 'RIPARIAN PENDING', 'COURTADJ OTHER',
       'PENDING OTHER', 'RIPARIAN COURTADJ OTHER',
       'RIPARIAN PRE1914 PENDING', 'PRE1914 COURTADJ OTHER',
       'RIPARIAN PENDING OTHER'], dtype=object)

In [12]:
# left-join water right / sites data -to- water use data

dfin1 = dfin1.merge(dfin2[['APPL_ID', 'AMOUNT', 'YEAR', 'MONTH FORMATTED']], left_on='APPLICATION_NUMBER', right_on='APPL_ID', how='left').reset_index(drop=True)
print(len(dfin1))
dfin1.head()

5229926

,ï»¿POD_ID,POD_NUMBER,POD_STATUS,SOURCE_TYPE,POD_NAME,POD_TYPE,DIVERSION_WORKS_STATUS,STREAM_CLASSIFICATION,DIRECT_DIV_AMOUNT,DIRECT_DIVERSION_RATE,DIRECT_DIV_RATE_UNIT,STORAGE_AMOUNT,DIVERSION_RATE_TO_OFF_STREAM,OFF_STO_DIV_RATE_UNIT,POD_LAST_UPDATE_DATE,POD_COUNT,APPL_ID_x,OBJECTID,POD_NUMBER_GIS,HAS_OPOD,APPL_POD,POD_ID_GIS,COUNTY,PARCEL_NUMBER,SP_ZONE,DIVERSION_SITE_NAME,NORTH_COORD,EAST_COORD,LATITUDE,LONGITUDE,QUARTER_QUARTER,QUARTER,SECTION_CLASSIFIER,SECTION_NUMBER,TOWNSHIP_NUMBER,TOWNSHIP_DIRECTION,RANGE_NUMBER,RANGE_DIRECTION,MERIDIAN,LOCATION_METHOD,SPECIAL_USE_AREA,SOURCE_NAME,TRIB_DESC,WATERSHED,HUC_12_NUMBER,HUC_12_NAME,HUC_8_NUMBER,HUC_8_NAME,QUAD_MAP_NAME,QUAD_MAP_NUMBER,WR_WATER_RIGHT_ID,APPLICATION_NUMBER,CERTIFICATE_ID,PERMIT_ID,LICENSE_ID,WATER_RIGHT_TYPE,WATER_RIGHT_STATUS,APPLICATION_NUMBER_PARTY,PWSS_ID,PRIORITY_DATE,RECEIPT_DATE,REJECTION_DATE,APPLICATION_RECD_DATE,APPLICATION_ACCEPTANCE_DATE,PROJECT_TYPE,RECORD_SUMMARY,INCOMPLETE_STATEMENT,NUMBER_OF_PROTESTS,AGENT_NAME,AGENT_ENTITY_TYPE,APPLICATION_PRIMARY_OWNER,PRIMARY_OWNER_ENTITY_TYPE,SUB_TYPE,INI_REPORTED_DIV_AMOUNT,INI_REPORTED_DIV_UNIT,FACE_VALUE_AMOUNT,FACE_VALUE_UNITS,FEE_DUE,FEE_RECEIVED,APPL_FEE_AMOUNT,APPL_FEE_AMT_RECD,MAX_DD_APPL,MAX_DD_UNITS,MAX_DD_ANN,MAX_STORAGE,MAX_TAKEN_FROM_SOURCE,YEAR_DIVERSION_COMMENCED,MAX_BENEFICIALLY_USED,SUPPLEMENTAL_STATEMENT_CYCLE,TYPE_OF_DIVERSION_FACILITY,QUANTITY_OF_WATER_DIVERTED,QOW_DIVERTED_UNIT,QUANTITY_MEASUREMENT_YEAR,MAX_RATE_OF_DIVERSION,MAX_RATE_OF_DIV_UNIT,RECENT_WATER_USE_MIN,WATER_USE_MIN_UNIT,RECENT_WATER_USE_MAX,WATER_USE_MAX_UNIT,REQUEST_FOR_REVOCATION_RECD,NUM_COMMENTS,NUM_ATTACHMENTS,LAST_UPDATE_DATE,STATE_WELL_NUMBER,DRILLED_WELL_YEAR,SURFACE_WATER_DIVERSIONS,DEPTH_OF_WELL,RELATIONSHIP_TYPE,PARTY_ID,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,PRIMARY_OWNER_NAME,PRIMARY_OWNER_ENTITY_TYPE_P,OFFICIAL_MAIL_RECEIVER,COUNT_NPO_OR_OTHER,CURRENT_STATUS,EFFECTIVE_DATE,UPDATE_DATETIME,USE_CODE,USE_STATUS,NUMBER_OF_RESIDENCES,SEPERATELY_OWNED,USE_POPULATION,USE_POPULATION_PEOPLE,ESTIMATED_USE_PER_PERSON,USE_POPULATION_STOCK,TYPE_OF_STOCK,AREA_FOR_INCI_IRRIGATION,USE_NET_ACREAGE,USE_GROSS_ACREAGE,USE_DIRECT_DIV_ANNUAL_AMOUNT,USE_DIRECT_DIVERSION_RATE,USE_DIRECT_DIV_RATE_UNITS,POU_DEVELOPMENT_STATUS,DIRECT_DIV_SEASON_START,DIRECT_DIV_SEASON_END,USE_STORAGE_AMOUNT,STORAGE_SEASON_START,STORAGE_SEASON_END,SEASON_DIRECT_DIV_RATE,SEASON_STORAGE_AMOUNT,SEASON_DIRECT_DIV_AA,DIRECT_DIV_SEASON_STATUS,COLLECTION_SEASON_STATUS,USE_COUNT,PERMIT_PERMIT_ID,PERMIT_ORIGINAL_ISSUE_DATE,COMPLETE_CONSTRUCTION_DATE,COMPLETE_APPLIC_WATER_DATE,LICENSE_LICENSE_ID,LICENSE_ORIGINAL_ISSUE_DATE,WATER_RIGHT_DESCRIPTION,PROGRAM_UNIT,LICENSE_REQUEST_TYPE,LICENSE_REQUESTED_DATE,INSPECTION_DATE,REPORT_DATE,OFFER_SENT_DATE,ACCEPTED_OFFER_DATE,PETITION_ID,PETITION_TYPE,PETITION_STATUS_TYPE,DATE_RECEIVED,DATE_COMPLETED,PET_LAST_UPDATE_DATE,NUM_OF_PETITIONS,ENF_CASE_NUMBER,ENF_CASE_START_DATE,ENF_CASE_CLOSURE_DATE,ENF_CASE_COUNTY,NUMBER_OF_ENFORCEMENT_CASE,WaDEUUID,in_WaterSourceTypeCV,in_VariableSpecificUUID,in_AllocationFlow_CFS,in_AllocationVolume_AF,wade_SUB_TYPE,APPL_ID_y,AMOUNT,YEAR,MONTH FORMATTED
0,60497,1.00000,Inactive,Surface,COMPOUND STOCK POND,Point of Direct Diversion,Existing,Unknown,48.00000,0.15000,Cubic Feet per Second,,,,,2,T032025,97404.00000,1.00000,N,T032025_01,60497,San Diego,,6.00000,COMPOUND STOCK POND,1814680.00000,6549776.00000,32.64560,-116.28860,NE,SW,,32.00000,17.00000,S,7.00000,E,San Bernardino,GIS_NE,,UNNAMED STREAM,BOUNDARY CREEK,ANZA BORREGO,181002020203.00000,Boundary Creek,18100202.00000,Carrizo Creek,LIVE OAK SPRINGS,,1,T032025,,,,Temporary Permit,Cancelled,T032025,,,4/18/2013,,4/18/2013,4/18/2013,,Migrated data from old WRIMS system.,,0,,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,,,,48.00000,Acre-feet per Year,1570.00000,1570.00000,1570.00000,1570.00000,0.15000,Cubic Feet per Second,48.00000,,0.00000,,0.00000,,,,,,,,,,,,N,1,1,,,,,0.00000,Primary Owner,539608.00000,4/18/2013,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,Y,0,Cancelled,8/9/2013,,Dust Control,Requested when filed,,,0.00000,,,,,,0.00000,0.00000,109.00000,0.15000,Cubic Feet per Second,Partial,1/1,12/31,0.00000,,,0.15000,0.00000,109.00000,Requested when filed,,1,,,,,,,,,,,,,,,,,,,,,,,,,,0,in10,Surface,CSWRCBwrwu_V1,0.15000,NaN,,NaN,NaN,NaN,NaN
1,60498,2.00000,Inactive,Surface,LAKE DOMINGO,Point of Direct Diversion,Proposed,Unknown,48.00000,0.15000,Cubic Feet per Second,,,,,2,T032025,95308.00000,2.00000,N,T032025_02,60498,San Diego,,6.00000,LAKE DOMINGO,1803326.00000,6554711.00000,32.61440,-116.27260,SE,SW,,9.00000,18.00000,S,7.00000,E,San Bernardino,GIS_NE,,LAKE DOMINGO,BOUNDARY CREEK,ANZA BORREGO,181002020203.00000,Boundary Creek,18100202.00000,Carrizo Creek,TIERRA DEL SOL,,1,T032025,,,,Temporary Permit,Cancelled,T032025,,,4/18/2013,,4/18/2013,4/18/2013,,Migrated data from old WRIMS system.,,0,,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,,,,48.00000,Acre-feet per Year,1570.00000,1570.00000,1570.00000,1570.00000,0.15000,Cubic Feet per Second,48.00000,,0.00000,,0.00000,,,,,,,,,,,,N,1,1,,,,,0.00000,Primary Owner,539608.00000,4/18/2013,,"569 EAST COUNTY BOULEVARD, LLC",Limited Liability Company,Y,0,Cancelled,8/9/2013,,Dust Control,Requested when filed,,,0.00000,,,,,,0.00000,0.00000,109.00000,0.15000,Cubic Feet per Second,Partial,1/1,12/31,0.00000,,,0.15000,0.00000,109.00000,Requested when filed,,1,,,,,,,,,,,,,,,,,,,,,,,,,,0,in11,Surface,CSWRCBwrwu_V1,0.15000,NaN,,NaN,NaN,NaN,NaN
2,404,1.00000,Active,,,Point of Direct Diversion,,,0.00000,0.02500,Cubic Feet per Second,0.00000,,,,4,A000016,58413.00000,1.00000,N,A000016_01,404,Los Angeles,,5.00000,,2032842.89063,6474612.14777,34.57797,-118.28921,NE,SE,,30.00000,6.00000,N,13.00000,W,San Bernardino,DD_NE,,ICY SPRING NO 1,,ANTELOPE,180902061401.00000,Headwaters Amargosa Creek,18090206.00000,Antelope-Fremont Valleys,SLEEPY VALLEY,OO071,2,A000016,41.00000,30.00000,41.00000,Appropriative,Licensed,A000016,,,,,,2/15/1915,,Migrated data from old WRIMS system.,,0,,,JUAN SERVIANO GARCIA LOPEZ,Individual,,,,18.10000,Acre-feet per Year,10.00000,10.00000,10.00000,10.00000,0.02500,Cubic Feet per Second,0.00000,0.00000,18.10000,,0.00000,,,,,,,,,,,,N,0,2,,,,,,Primary Owner,650859.00000,4/9/2025,,JUAN GARCIA LOPEZ,Individual,Y,3,Licensed,2/19/1915,,Domestic,Migrated from old WRIMS data,,,0.00000,,,,,,0.00000,0.00000,0.00000,0.00000,,,1/1,12/31,0.00000,,,,0.00000,,Migrated from old WRIMS data,Migrated from old WRIMS data,2,30.00000,10/28/1915,,,41.00000,9/25/1918,Migrated data from old WRIMS system.,,Permitee Request,,,,,,,,,,,,,,,,,0,in12,WaDE Blank,CSWRCBwrwu_V1,NaN,NaN,,NaN,NaN,NaN,NaN
3,17603,1.00000,Active,,,Point of Direct Diversion,,,0.00000,0.02500,Cubic Feet per Second,0.00000,,,,4,A000016,58414.00000,1.00000,N,A000016_01,17603,Los Angeles,,5.00000,,2032842.89063,6474612.14777,34.57797,-118.28921,NE,SE,,30.00000,6.00000,N,13.00000,W,San Bernardino,DD_NE,,KERR SPRING NO 2,,ANTELOPE,180902061401.00000,Headwaters Amargosa Creek,18090206.00000,Antelope-Fremont Valleys,SLEEPY VALLEY,OO071,2,A000016,41.00000,30.00000,41.00000,Appropriative,Licensed,A000016,,,,,,2/15/1915,,Migrated data from old WRIMS system.,,0,,,JUAN SERVIANO GARCIA LOPEZ,Individual,,,,18.10000,Acre-feet per Year,10.00000,10.00000,10.00000,10.00000,0.02500,Cubic Feet per Second,0.00000,0.00000,18.10000,,0.00000,,,,,,,,,,,,N,0,2,,,,,,Primary Owner,650859.00000,4/9/2025,,JUAN GARCIA LOPEZ,Individual,Y,3,Licensed,2/19/1915,,Domestic,Migrated from old WRIMS data,,,0.00000,,,,,,0.00000,0.00000,0.00000,0.00000,,,1/1,12/31,0.00000,,,,0.00000,,Migrated from old WRIMS data,Migrated from old WRIMS data,2,30.00000,10/28/1915,,,41.00000,9/25/1918,Migrated data from old WRIMS system.,,Permitee Request,,,,,,,,,,,,,,,,,0,in13,WaDE Blank,CSWRCBwrwu_V1,NaN,NaN,,NaN,NaN,NaN,NaN
4,29028,1.00000,Active,,,Point of Direct Diversion,,,0.00000,0.02500,Cubic Feet per Second,0.00000,,,,4,A000016,57787.00000,1.00000,N,A000016_01,29028,Los Angeles,005-370-43-00,5.00000,,2033642.80241,6474614.80623,34.58017,-118.28921,SE,NE,,30.00000,6.00000,N,13.00000,W,San Bernardino,DD_NE,,KERR SPRING NO 1,,ANTELOPE,180902061401.00000,Headwaters Amargosa Creek,18090206.00000,Antelope-Fremont Valleys,SLEEPY VALLEY,OO071,2,A000016,41.00000,30.00000,41.00000,Appropriative,Licensed,A000016,,,,,,2/15/1915,,Migrated data from old WRIMS system.,,0,,,JUAN SERVIANO GARCIA LOPEZ,Individual,,,,18.10000,Acre-feet per Year,10.00000,10.00000,10.00000,10.00000,0.02500,Cubic Feet per Second,0.00000,0.00000,18.10000,,0.00000,,,,,,,,,,,,N,0,2,,,,,,Primary Owner,650859.00000,4/9/2025,,JUAN GARCIA LOPEZ,Individual,Y,3,Licensed,2/19/1915,,Domestic,Migrated from old WRIMS data,,,0.00000,,,,,,0.00000,0.00000,0.00000,0.00000,,,1/1,12/31,0.00000,,,,0.00000,,Migrated from old WRIMS data,Migrated from old WRIMS data,2,30.00000,10/28/1915,,,41.00000,9/25/1918,Migrated data from old WRIMS system.,,Permitee Request,,,,,,,,,,,,,,,,,0,in14,WaDE Blank,CSWRCBwrwu_V1,NaN,NaN,,NaN,NaN,NaN,NaN

In [13]:
# create output POD dataframe
outdf1 = pd.DataFrame()

# Data Assessment UUID
outdf1['WaDEUUID'] = dfin1['WaDEUUID']

# Method Info
outdf1['in_MethodUUID'] = "CSWRCBwrwu_M1"

# Variable Info
outdf1['in_VariableSpecificUUID'] = dfin1['in_VariableSpecificUUID'] # for wr records portion only, will create sa portion below
outdf1['in_AggregationIntervalUnitCV'] = "Monthly"
outdf1['in_VariableCV'] = "Water Right Use"

# Organization Info
outdf1['in_OrganizationUUID'] = "CSWRCBwrwu_O1"

# WaterSource Info
outdf1['in_Geometry'] = ""
outdf1['in_GNISFeatureNameCV'] = ""
outdf1['in_WaterQualityIndicatorCV'] = ""
outdf1['in_WaterSourceName'] = dfin1['SOURCE_NAME'].str.title()
outdf1['in_WaterSourceNativeID'] = "" # create customID for temp solution
outdf1['in_WaterSourceTypeCV'] = dfin1['in_WaterSourceTypeCV'] # see above

# Site Info
outdf1['in_OverlayUUIDs'] = ""
outdf1['in_WaterSourceUUID'] = "" # ???
outdf1['in_CoordinateAccuracy'] = ""
outdf1['in_CoordinateMethodCV'] = dfin1['LOCATION_METHOD']
outdf1['in_County'] = dfin1['COUNTY'].str.title()
outdf1['in_EPSGCodeCV'] = 4326
outdf1['in_Geometry'] = ""
outdf1['in_GNISCodeCV'] = ""
outdf1['in_HUC12'] = dfin1['HUC_12_NUMBER'].replace("", 0).fillna(0).astype('int64').astype(str)
outdf1['in_HUC8'] = dfin1['HUC_8_NUMBER'].replace("", 0).fillna(0).astype('int64').astype(str)
outdf1['in_Latitude'] = dfin1['LATITUDE']
outdf1['in_Longitude'] = dfin1['LONGITUDE']
outdf1['in_NHDNetworkStatusCV'] = ""
outdf1['in_NHDProductCV'] = ""
outdf1['in_PODorPOUSite'] = "POD"
outdf1['in_SiteName'] = dfin1['POD_NAME'].str.title().str.replace(",", "")
outdf1['in_SiteNativeID'] = dfin1['ï»¿POD_ID'].replace("", 0).fillna(0).astype('int64').astype(str)
outdf1['in_SitePoint'] = ""
outdf1['in_SiteTypeCV'] = "WaDE Blank"
outdf1['in_StateCV'] = "CA"
outdf1['in_USGSSiteID'] = ""

# AllocationAmount Info
outdf1['in_AllocationApplicationDate'] = dfin1['APPLICATION_RECD_DATE']
outdf1['in_AllocationAssociatedConsumptiveUseSiteIDs'] = ""
outdf1['in_AllocationAssociatedWithdrawalSiteIDs'] = ""
outdf1['in_AllocationBasisCV'] = ""
outdf1['in_AllocationChangeApplicationIndicator'] = ""
outdf1['in_AllocationCommunityWaterSupplySystem'] = ""
outdf1['in_AllocationCropDutyAmount'] = ""
outdf1['in_AllocationExpirationDate'] = ""
outdf1['in_AllocationFlow_CFS'] = dfin1['in_AllocationFlow_CFS'].astype(float) # see above for conversion
outdf1['in_AllocationLegalStatusCV'] = dfin1['WATER_RIGHT_STATUS'].str.title()
outdf1['in_AllocationNativeID'] =  dfin1['APPLICATION_NUMBER'].replace("", 0).fillna(0).astype(str)
outdf1['in_AllocationOwner'] = dfin1['PRIMARY_OWNER_NAME']
outdf1['in_AllocationPriorityDate'] = dfin1['PRIORITY_DATE']
outdf1['in_AllocationSDWISIdentifierCV'] = ""
outdf1['in_AllocationTimeframeEnd'] = dfin1['DIRECT_DIV_SEASON_END']
outdf1['in_AllocationTimeframeStart'] = dfin1['DIRECT_DIV_SEASON_START']
outdf1['in_AllocationTypeCV'] = dfin1['WATER_RIGHT_TYPE'].astype(str) + " " + dfin1['wade_SUB_TYPE'].astype(str)
outdf1['in_AllocationTypeCV'] = outdf1['in_AllocationTypeCV'].astype(str).str.strip()
outdf1['in_AllocationVolume_AF'] = dfin1['in_AllocationVolume_AF'].astype(float) # see above for conversion
outdf1['in_BeneficialUseCategory'] = dfin1['USE_CODE'].str.title()
outdf1['in_CommunityWaterSupplySystem'] = ""
outdf1['in_CropTypeCV'] = ""
outdf1['in_CustomerTypeCV'] = ""
outdf1['in_DataPublicationDate'] = ""
outdf1['in_DataPublicationDOI'] = ""
outdf1['in_ExemptOfVolumeFlowPriority'] = "1" # we want this data to be exempt
outdf1['in_GeneratedPowerCapacityMW'] = ""
outdf1['in_IrrigatedAcreage'] = "" # temp fix, leave blank for now
outdf1['in_IrrigationMethodCV'] = ""
outdf1['in_LegacyAllocationIDs'] = ""
outdf1['in_OwnerClassificationCV'] = ""
outdf1['in_PopulationServed'] = "" # temp fix, leave blank for now
outdf1['in_PowerType'] = ""
outdf1['in_PrimaryBeneficialUseCategory'] = ""
outdf1['in_SDWISIdentifierCV'] = ""
outdf1['in_WaterAllocationNativeURL'] = "https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/EWServlet?Redirect_Page=EWPublicAppSummary.jsp&Purpose=getEwrimsPublicSummary&wrWaterRightID=" + dfin1['WR_WATER_RIGHT_ID'].replace("", 0).fillna(0).astype(int).astype(str)


# Site VariableAmounts Info
outdf1['in_Amount'] = dfin1['AMOUNT']
outdf1['in_AssociatedNativeAllocationIDs'] = dfin1['APPLICATION_NUMBER']
outdf1['in_PowerGeneratedGWh'] = ""
outdf1['in_PrimaryUseCategory'] = "" # see below
outdf1['in_ReportYearCV'] = dfin1['YEAR'].replace("", 0).fillna(0).astype(int).astype(str)
outdf1['in_SDWISIdentifier'] = ""
outdf1['in_TimeframeEnd'] = dfin1['MONTH FORMATTED']
outdf1['in_TimeframeStart'] = dfin1['MONTH FORMATTED']
# outdf1['in_AllocationCropDutyAmount'] = "" see above AllocationAmount Info
# outdf1['in_BeneficialUseCategory'] = "" see above AllocationAmount Info
# outdf1['in_CommunityWaterSupplySystem'] = "" see above AllocationAmount Info
# outdf1['in_CropTypeCV'] = "" see above AllocationAmount Info
# outdf1['in_CustomerTypeCV'] = "" see above AllocationAmount Info
# outdf1['in_DataPublicationDate'] = "" see above AllocationAmount Info
# outdf1['in_DataPublicationDOI'] = "" see above AllocationAmount Info
# outdf1['in_Geometry'] = "" see above Site Info
# outdf1['in_IrrigatedAcreage'] = "" see above AllocationAmount Info
# outdf1['in_IrrigationMethodCV'] = "" see above AllocationAmount Info
# outdf1['in_PopulationServed'] = "" see above AllocationAmount Info
# outdf1['in_PowerType'] = "" see above AllocationAmount Info
# outdf1['in_SDWISIdentifier'] = "" see above AllocationAmount Info

outdf1 = outdf1.drop_duplicates().reset_index(drop=True)
outdf1 = outdf1.fillna("")
print(len(outdf1))
outdf1.head()

C:\Users\rjame\AppData\Local\Temp\ipykernel_2832\1091086086.py:35: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  outdf1['in_HUC12'] = dfin1['HUC_12_NUMBER'].replace("", 0).fillna(0).astype('int64').astype(str)
C:\Users\rjame\AppData\Local\Temp\ipykernel_2832\1091086086.py:36: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  outdf1['in_HUC8'] = dfin1['HUC_8_NUMBER'].replace("", 0).fillna(0).astype('int64').astype(str)

2997930

,WaDEUUID,in_MethodUUID,in_VariableSpecificUUID,in_AggregationIntervalUnitCV,in_VariableCV,in_OrganizationUUID,in_Geometry,in_GNISFeatureNameCV,in_WaterQualityIndicatorCV,in_WaterSourceName,in_WaterSourceNativeID,in_WaterSourceTypeCV,in_OverlayUUIDs,in_WaterSourceUUID,in_CoordinateAccuracy,in_CoordinateMethodCV,in_County,in_EPSGCodeCV,in_GNISCodeCV,in_HUC12,in_HUC8,in_Latitude,in_Longitude,in_NHDNetworkStatusCV,in_NHDProductCV,in_PODorPOUSite,in_SiteName,in_SiteNativeID,in_SitePoint,in_SiteTypeCV,in_StateCV,in_USGSSiteID,in_AllocationApplicationDate,in_AllocationAssociatedConsumptiveUseSiteIDs,in_AllocationAssociatedWithdrawalSiteIDs,in_AllocationBasisCV,in_AllocationChangeApplicationIndicator,in_AllocationCommunityWaterSupplySystem,in_AllocationCropDutyAmount,in_AllocationExpirationDate,in_AllocationFlow_CFS,in_AllocationLegalStatusCV,in_AllocationNativeID,in_AllocationOwner,in_AllocationPriorityDate,in_AllocationSDWISIdentifierCV,in_AllocationTimeframeEnd,in_AllocationTimeframeStart,in_AllocationTypeCV,in_AllocationVolume_AF,in_BeneficialUseCategory,in_CommunityWaterSupplySystem,in_CropTypeCV,in_CustomerTypeCV,in_DataPublicationDate,in_DataPublicationDOI,in_ExemptOfVolumeFlowPriority,in_GeneratedPowerCapacityMW,in_IrrigatedAcreage,in_IrrigationMethodCV,in_LegacyAllocationIDs,in_OwnerClassificationCV,in_PopulationServed,in_PowerType,in_PrimaryBeneficialUseCategory,in_SDWISIdentifierCV,in_WaterAllocationNativeURL,in_Amount,in_AssociatedNativeAllocationIDs,in_PowerGeneratedGWh,in_PrimaryUseCategory,in_ReportYearCV,in_SDWISIdentifier,in_TimeframeEnd,in_TimeframeStart
0,in10,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Unnamed Stream,,Surface,,,,GIS_NE,San Diego,4326,,181002020203,18100202,32.64560,-116.28860,,,POD,Compound Stock Pond,60497,,WaDE Blank,CA,,4/18/2013,,,,,,,,0.15000,Cancelled,T032025,"569 EAST COUNTY BOULEVARD, LLC",,,12/31,1/1,Temporary Permit,,Dust Control,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,T032025,,,0,,,
1,in11,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Lake Domingo,,Surface,,,,GIS_NE,San Diego,4326,,181002020203,18100202,32.61440,-116.27260,,,POD,Lake Domingo,60498,,WaDE Blank,CA,,4/18/2013,,,,,,,,0.15000,Cancelled,T032025,"569 EAST COUNTY BOULEVARD, LLC",,,12/31,1/1,Temporary Permit,,Dust Control,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,T032025,,,0,,,
2,in12,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Icy Spring No 1,,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.57797,-118.28921,,,POD,,404,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,JUAN GARCIA LOPEZ,,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,,0,,,
3,in13,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Kerr Spring No 2,,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.57797,-118.28921,,,POD,,17603,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,JUAN GARCIA LOPEZ,,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,,0,,,
4,in14,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Kerr Spring No 1,,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.58017,-118.28921,,,POD,,29028,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,JUAN GARCIA LOPEZ,,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,,0,,,

## Concatenate POD and POU Data.  Make needed changes

In [14]:
# etc etc,
# outdf2

## Concatenate DataFrames together

In [15]:
# Concatenate dataframes
frames = [outdf1]  # list all out dataframes here
outdf = pd.concat(frames)
outdf = outdf.drop_duplicates().reset_index(drop=True).replace(np.nan, "")
print(len(outdf))

2997930

## Clean Data / data types

In [16]:
# Fill empty ben use values

def fillEmptyBenUseFunc(val):
    val = str(val).strip()
    if val == "" or val == " " or val == "nan" or pd.isnull(val):
        outString = "Unspecified"
    else:
        outString = val
    return outString
    
outdf['in_BeneficialUseCategory'] = outdf.apply(lambda row: fillEmptyBenUseFunc(row['in_BeneficialUseCategory']), axis=1)
outdf['in_PrimaryUseCategory'] = outdf.apply(lambda row: fillEmptyBenUseFunc(row['in_PrimaryUseCategory']), axis=1)
outdf['in_BeneficialUseCategory'].unique()

array(['Dust Control', 'Domestic', 'Irrigation', 'Power', 'Municipal',
       'Fish And Wildlife Preservation And Enhancement', 'Stockwatering',
       'Industrial', 'Mining', 'Recreational', 'Fire Protection',
       'Incidental Power', 'Frost Protection', 'Aquaculture',
       'Snow Making', 'Milling', 'Heat Control', 'Other', 'Unspecified',
       'Aesthetic', 'Water Quality'], dtype=object)

In [17]:
# Update datatype of Priority Date to fit WaDE 2.0 structure
def formatDateString(inString1):
    inString = str(inString1).strip()
    try:
        if inString == "" or pd.isnull(inString):
            valndf = ""
        else:
            valD = pd.to_datetime(inString)
            valnDd = valD.date()
            valndf = valnDd.strftime('%m/%d/%Y')
    except:
        valndf = ""
    return valndf

outdf['in_AllocationPriorityDate'] = outdf.apply(lambda row: formatDateString(row['in_AllocationPriorityDate']), axis=1)
outdf['in_AllocationPriorityDate'].unique()

array(['', '07/22/1915', '04/17/1916', ..., '04/28/2025', '03/28/2022',
       '10/26/2021'], shape=(2083,), dtype=object)

In [18]:
# Clean name entries of spcial characters
def removeSpecialCharsFunc(Val):
    Val = str(Val)
    Val = re.sub("[$@&.;/\)(-]", "", Val).title().replace("  ", " ").strip()
    return Val

<>:4: SyntaxWarning: invalid escape sequence '\)'
<>:4: SyntaxWarning: invalid escape sequence '\)'
C:\Users\rjame\AppData\Local\Temp\ipykernel_2832\297602357.py:4: SyntaxWarning: invalid escape sequence '\)'
  Val = re.sub("[$@&.;/\)(-]", "", Val).title().replace("  ", " ").strip()

In [19]:
outdf['in_WaterSourceName'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_WaterSourceName']), axis=1)
outdf['in_WaterSourceName'].unique()

array(['Unnamed Stream', 'Lake Domingo', 'Icy Spring No 1', ...,
       'East Etiwanda Canyon', 'Mill Creek South',
       'Unnamed Spring, Tributary To Unnamed Stream, Thence Redwood Creek'],
      shape=(8738,), dtype=object)

In [20]:
outdf['in_County'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_County']), axis=1)
outdf['in_County'].unique()

array(['San Diego', 'Los Angeles', 'Glenn', 'Colusa', 'Madera', 'Fresno',
       'Merced', 'Alameda', 'Contra Costa', 'Lake', 'Mono', 'Lassen',
       'Tuolumne', 'Riverside', 'San Bernardino', 'Inyo', 'Modoc',
       'Sacramento', 'El Dorado', 'Trinity', 'San Luis Obispo',
       'Santa Clara', 'Shasta', 'Tulare', 'Kern', 'San Joaquin', 'Tehama',
       'Kings', 'Stanislaus', 'Siskiyou', 'Butte', 'Yuba', 'Sierra',
       'Napa', 'Sutter', 'Placer', 'Ventura', 'Yolo', 'Alpine', 'Plumas',
       'Santa Barbara', 'Mendocino', 'Sonoma', 'Calaveras', 'Mariposa',
       'Humboldt', 'Nevada', 'Amador', 'San Benito', 'Solano',
       'Santa Cruz', 'Monterey', 'Marin', 'San Mateo', '', 'Orange',
       'Imperial', 'Del Norte', 'San Francisco'], dtype=object)

In [21]:
outdf['in_SiteName'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_SiteName']), axis=1)
outdf['in_SiteName'].unique()

array(['Compound Stock Pond', 'Lake Domingo', '', ...,
       'Wildhorse Well #2 Cauley', 'Harrell Ranch No 1', 'Mckay Ditch'],
      shape=(7736,), dtype=object)

In [22]:
outdf['in_AllocationOwner'] = outdf.apply(lambda row: removeSpecialCharsFunc(row['in_AllocationOwner']), axis=1)
outdf['in_AllocationOwner'].unique()

array(['569 East County Boulevard, Llc', 'Juan Garcia Lopez',
       'Glenncolusa Irrigation District', ...,
       'Wilcox Family Investments', 'Jerry J Rava Ii Trust',
       'Frank Hutchinson'], shape=(21371,), dtype=object)

In [23]:
# Ensure Empty String / remove string value of "nan"

def ensureEmptyString(val):
    val = str(val).strip()
    if val == "" or val == " " or val == "nan" or pd.isnull(val):
        outString = ""
    else:
        outString = val
    return outString

In [24]:
outdf['in_WaterSourceName'] = outdf.apply(lambda row: ensureEmptyString(row['in_WaterSourceName']), axis=1)
outdf['in_WaterSourceName'].unique()

array(['Unnamed Stream', 'Lake Domingo', 'Icy Spring No 1', ...,
       'East Etiwanda Canyon', 'Mill Creek South',
       'Unnamed Spring, Tributary To Unnamed Stream, Thence Redwood Creek'],
      shape=(8738,), dtype=object)

In [25]:
outdf['in_WaterSourceTypeCV'] = outdf.apply(lambda row: ensureEmptyString(row['in_WaterSourceTypeCV']), axis=1)
outdf['in_WaterSourceTypeCV'].unique()

array(['Surface', 'WaDE Blank', 'Subsurface'], dtype=object)

In [26]:
outdf['in_SiteTypeCV'] = outdf.apply(lambda row: ensureEmptyString(row['in_SiteTypeCV']), axis=1)
outdf['in_SiteTypeCV'].unique()

array(['WaDE Blank'], dtype=object)

In [27]:
outdf['in_SiteName'] = outdf.apply(lambda row: ensureEmptyString(row['in_SiteName']), axis=1)
outdf['in_SiteName'].unique()

array(['Compound Stock Pond', 'Lake Domingo', '', ...,
       'Wildhorse Well #2 Cauley', 'Harrell Ranch No 1', 'Mckay Ditch'],
      shape=(7736,), dtype=object)

In [28]:
outdf['in_County'] = outdf.apply(lambda row: ensureEmptyString(row['in_County']), axis=1)
outdf['in_County'].unique()

array(['San Diego', 'Los Angeles', 'Glenn', 'Colusa', 'Madera', 'Fresno',
       'Merced', 'Alameda', 'Contra Costa', 'Lake', 'Mono', 'Lassen',
       'Tuolumne', 'Riverside', 'San Bernardino', 'Inyo', 'Modoc',
       'Sacramento', 'El Dorado', 'Trinity', 'San Luis Obispo',
       'Santa Clara', 'Shasta', 'Tulare', 'Kern', 'San Joaquin', 'Tehama',
       'Kings', 'Stanislaus', 'Siskiyou', 'Butte', 'Yuba', 'Sierra',
       'Napa', 'Sutter', 'Placer', 'Ventura', 'Yolo', 'Alpine', 'Plumas',
       'Santa Barbara', 'Mendocino', 'Sonoma', 'Calaveras', 'Mariposa',
       'Humboldt', 'Nevada', 'Amador', 'San Benito', 'Solano',
       'Santa Cruz', 'Monterey', 'Marin', 'San Mateo', '', 'Orange',
       'Imperial', 'Del Norte', 'San Francisco'], dtype=object)

In [29]:
outdf['in_AllocationOwner'] = outdf.apply(lambda row: ensureEmptyString(row['in_AllocationOwner']), axis=1)
outdf['in_AllocationOwner'].unique()

array(['569 East County Boulevard, Llc', 'Juan Garcia Lopez',
       'Glenncolusa Irrigation District', ...,
       'Wilcox Family Investments', 'Jerry J Rava Ii Trust',
       'Frank Hutchinson'], shape=(21371,), dtype=object)

In [30]:
outdf['in_BeneficialUseCategory'] = outdf.apply(lambda row: ensureEmptyString(row['in_BeneficialUseCategory']), axis=1)
uniqueList = list(set([i.strip() for i in ','.join(outdf['in_BeneficialUseCategory'].astype(str)).split(',')]))
uniqueList.sort()
uniqueList

['Aesthetic',
 'Aquaculture',
 'Domestic',
 'Dust Control',
 'Fire Protection',
 'Fish And Wildlife Preservation And Enhancement',
 'Frost Protection',
 'Heat Control',
 'Incidental Power',
 'Industrial',
 'Irrigation',
 'Milling',
 'Mining',
 'Municipal',
 'Other',
 'Power',
 'Recreational',
 'Snow Making',
 'Stockwatering',
 'Unspecified',
 'Water Quality']

In [31]:
# Ensure Latitude entry is numireic, replace '0' values for removal
outdf['in_Latitude'] = pd.to_numeric(outdf['in_Latitude'], errors='coerce').replace(0,"").fillna("")
outdf['in_Latitude'].unique()

array([32.6456, 32.6144, 34.57797187, ..., 40.878983, 39.042593,
       40.592592], shape=(50836,), dtype=object)

In [32]:
# Ensure Longitude entry is numireic, replace '0' values for removal
outdf['in_Longitude'] = pd.to_numeric(outdf['in_Longitude'], errors='coerce').replace(0,"").fillna("")
outdf['in_Longitude'].unique()

array([-116.2886, -116.2726, -118.28920963, ..., -123.752027, -120.120175,
       -122.927895], shape=(50772,), dtype=object)

In [33]:
# Fixing in_AllocationFlow_CFS datatype
outdf['in_AllocationFlow_CFS'] = pd.to_numeric(outdf['in_AllocationFlow_CFS'], errors='coerce').replace(0,"").fillna("")
outdf['in_AllocationFlow_CFS'].unique()

array([0.15, '', 373.0, ..., 0.5926504614196024, 6.906828685717171, 266.0],
      shape=(1590,), dtype=object)

In [34]:
# Fixing in_AllocationVolume_AF datatype
outdf['in_AllocationVolume_AF'] = pd.to_numeric(outdf['in_AllocationVolume_AF'], errors='coerce').replace(0,"").fillna("")
outdf['in_AllocationVolume_AF'].unique()

array(['', 0.13, 365.0, 20.62], dtype=object)

In [35]:
# Ensure Amount entry is either numireic or blank, no 0 entries
outdf['in_Amount'] = pd.to_numeric(outdf['in_Amount'], errors='coerce').round(2).replace(0,"").fillna("")
outdf['in_Amount'].unique()

array(['', 540.0, 129.0, ..., 10783.0, 18557.0, 18823.0],
      shape=(38120,), dtype=object)

In [36]:
# Ensure PopulationServed entry is numireic WITH 0 entries (no blank strings)
outdf['in_PopulationServed'] = pd.to_numeric(outdf['in_PopulationServed'], errors='coerce').round().replace("",0).fillna(0).astype(int).replace(0,"").fillna("")
outdf['in_PopulationServed'].unique()

array([''], dtype=object)

In [58]:
# Changing datatype of Priority Date to date fields entry
outdf['in_AllocationPriorityDate'] = pd.to_datetime(outdf['in_AllocationPriorityDate'], errors = 'coerce')
outdf['in_AllocationPriorityDate'] = pd.to_datetime(outdf["in_AllocationPriorityDate"].dt.strftime('%m/%d/%Y'))
outdf['in_AllocationPriorityDate'].unique()

<DatetimeArray>
[                'NaT', '1915-07-22 00:00:00', '1916-04-17 00:00:00',
 '1917-01-03 00:00:00', '1917-07-12 00:00:00', '1918-12-31 00:00:00',
 '1919-02-26 00:00:00', '1919-10-10 00:00:00', '1920-02-11 00:00:00',
 '1920-07-23 00:00:00',
 ...
 '2024-09-23 00:00:00', '2024-10-01 00:00:00', '1979-01-16 00:00:00',
 '2024-01-22 00:00:00', '2024-02-01 00:00:00', '2023-12-03 00:00:00',
 '2025-01-06 00:00:00', '2024-09-09 00:00:00', '2023-03-15 00:00:00',
 '2024-01-10 00:00:00']
Length: 1590, dtype: datetime64[ns]

In [54]:
# Convert TimeframeEnd to YYYY-MM-DD format.
outdf['in_TimeframeEnd'] = pd.to_datetime(outdf['in_TimeframeEnd'], utc=True, errors = 'coerce').fillna("")
outdf['in_TimeframeEnd'] = pd.to_datetime(outdf["in_TimeframeEnd"].dt.strftime('%m/%d/%Y'))
outdf['in_TimeframeEnd'].unique()

<DatetimeArray>
[                'NaT', '2017-05-01 00:00:00', '2017-06-01 00:00:00',
 '2017-07-01 00:00:00', '2017-08-01 00:00:00', '2017-09-01 00:00:00',
 '2017-10-01 00:00:00', '2017-11-01 00:00:00', '2017-12-01 00:00:00',
 '2018-01-01 00:00:00',
 ...
 '1991-08-01 00:00:00', '1992-08-01 00:00:00', '1991-09-01 00:00:00',
 '1992-09-01 00:00:00', '1991-10-01 00:00:00', '1992-10-01 00:00:00',
 '1991-11-01 00:00:00', '1992-11-01 00:00:00', '1991-12-01 00:00:00',
 '1992-12-01 00:00:00']
Length: 421, dtype: datetime64[ns]

In [55]:
# Convert TimeframeStart to YYYY-MM-DD format.
outdf['in_TimeframeStart'] = pd.to_datetime(outdf['in_TimeframeStart'], utc=True, errors = 'coerce').fillna("")
outdf['in_TimeframeStart'] = pd.to_datetime(outdf["in_TimeframeStart"].dt.strftime('%m/%d/%Y'))
outdf['in_TimeframeStart'].unique()

<DatetimeArray>
[                'NaT', '2017-05-01 00:00:00', '2017-06-01 00:00:00',
 '2017-07-01 00:00:00', '2017-08-01 00:00:00', '2017-09-01 00:00:00',
 '2017-10-01 00:00:00', '2017-11-01 00:00:00', '2017-12-01 00:00:00',
 '2018-01-01 00:00:00',
 ...
 '1991-08-01 00:00:00', '1992-08-01 00:00:00', '1991-09-01 00:00:00',
 '1992-09-01 00:00:00', '1991-10-01 00:00:00', '1992-10-01 00:00:00',
 '1991-11-01 00:00:00', '1992-11-01 00:00:00', '1991-12-01 00:00:00',
 '1992-12-01 00:00:00']
Length: 421, dtype: datetime64[ns]

In [40]:
# extract year out
outdf['in_ReportYearCV'].unique()

array(['0', '2017', '2018', '2019', '2022', '2023', '2024', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2020',
       '2021', '2008', '2007', '2006', '1975', '2002', '2003', '2004',
       '2005', '2000', '2001', '1930', '1996', '1997', '1998', '1999',
       '1993', '1994', '1995', '1991', '1992'], dtype=object)

In [41]:
# Assign Primary Use Category

import sys
sys.path.append("C:/Users/rjame/Documents/WSWC Documents/MappingStatesDataToWaDE2.0/5_CustomFunctions/AssignPrimaryUseCategory")
import AssignPrimaryUseCategoryFile # Use Custom import file

outdf['in_PrimaryUseCategory'] = outdf.apply(lambda row: AssignPrimaryUseCategoryFile.retrievePrimaryUseCategory(row['in_BeneficialUseCategory']), axis=1)
outdf['in_PrimaryUseCategory'].unique()

array(['Other', 'Domestic', 'Agriculture Irrigation', 'Hydroelectric',
       'Public Supply', 'In-stream Flow', 'Livestock',
       'Commercial/Industrial', 'Mining', 'Recreation', 'Fire',
       'Unspecified', 'Aquaculture', 'Snow', 'Thermoelectric Cooling',
       'Municipal Irrigation'], dtype=object)

In [42]:
# Creating WaDE Custom VariableSpecificCV
# ----------------------------------------------------------------------------------------------------
def createVariableSpecificCV(inV, inAIU, inPU, inWST):
    inV = str(inV).strip()
    inAIU = str(inAIU).strip()
    inPU = str(inPU).strip().title()
    inWST = str(inWST).strip()
    outString = inV + "_" + inAIU + "_" + inPU + "_" + inWST
    return outString

outdf['in_VariableSpecificCV'] = outdf.apply(lambda row: createVariableSpecificCV(row['in_VariableCV'], 
                                                                                  row['in_AggregationIntervalUnitCV'],
                                                                                  row['in_PrimaryUseCategory'],
                                                                                  row['in_WaterSourceTypeCV']), axis=1)
outdf['in_VariableSpecificCV'].unique()

array(['Water Right Use_Monthly_Other_Surface',
       'Water Right Use_Monthly_Domestic_WaDE Blank',
       'Water Right Use_Monthly_Agriculture Irrigation_Surface',
       'Water Right Use_Monthly_Domestic_Surface',
       'Water Right Use_Monthly_Domestic_Subsurface',
       'Water Right Use_Monthly_Hydroelectric_Subsurface',
       'Water Right Use_Monthly_Hydroelectric_Surface',
       'Water Right Use_Monthly_Agriculture Irrigation_Subsurface',
       'Water Right Use_Monthly_Agriculture Irrigation_WaDE Blank',
       'Water Right Use_Monthly_Public Supply_Surface',
       'Water Right Use_Monthly_In-Stream Flow_WaDE Blank',
       'Water Right Use_Monthly_Livestock_WaDE Blank',
       'Water Right Use_Monthly_Commercial/Industrial_Surface',
       'Water Right Use_Monthly_Mining_WaDE Blank',
       'Water Right Use_Monthly_Hydroelectric_WaDE Blank',
       'Water Right Use_Monthly_Recreation_Surface',
       'Water Right Use_Monthly_In-Stream Flow_Surface',
       'Water Right Use_Monthly_In-Stream Flow_Subsurface',
       'Water Right Use_Monthly_Commercial/Industrial_Subsurface',
       'Water Right Use_Monthly_Livestock_Subsurface',
       'Water Right Use_Monthly_Livestock_Surface',
       'Water Right Use_Monthly_Mining_Surface',
       'Water Right Use_Monthly_Fire_WaDE Blank',
       'Water Right Use_Monthly_Fire_Subsurface',
       'Water Right Use_Monthly_Public Supply_Subsurface',
       'Water Right Use_Monthly_Unspecified_Surface',
       'Water Right Use_Monthly_Unspecified_Subsurface',
       'Water Right Use_Monthly_Public Supply_WaDE Blank',
       'Water Right Use_Monthly_Other_Subsurface',
       'Water Right Use_Monthly_Commercial/Industrial_WaDE Blank',
       'Water Right Use_Monthly_Aquaculture_Surface',
       'Water Right Use_Monthly_Unspecified_WaDE Blank',
       'Water Right Use_Monthly_Aquaculture_WaDE Blank',
       'Water Right Use_Monthly_Snow_WaDE Blank',
       'Water Right Use_Monthly_Fire_Surface',
       'Water Right Use_Monthly_Other_WaDE Blank',
       'Water Right Use_Monthly_Recreation_WaDE Blank',
       'Water Right Use_Monthly_Recreation_Subsurface',
       'Water Right Use_Monthly_Thermoelectric Cooling_Surface',
       'Water Right Use_Monthly_Aquaculture_Subsurface',
       'Water Right Use_Monthly_Thermoelectric Cooling_Subsurface',
       'Water Right Use_Monthly_Mining_Subsurface',
       'Water Right Use_Monthly_Snow_Surface',
       'Water Right Use_Monthly_Thermoelectric Cooling_WaDE Blank',
       'Water Right Use_Monthly_Municipal Irrigation_Surface',
       'Water Right Use_Monthly_Municipal Irrigation_Subsurface'],
      dtype=object)

In [43]:
# Creating WaDE Custom water source native ID for easy water source identification
# use unique WaterSourceName and WaterSourceType values
# ----------------------------------------------------------------------------------------------------

# Create temp in_WaterSourceNativeID dataframe of unique water source.
def assignIdValueFunc(colRowValue):
    string1 = str(colRowValue)
    outstring = "wadeId" + string1
    return outstring

dfTempID = pd.DataFrame()
dfTempID['in_WaterSourceName'] = outdf['in_WaterSourceName'].astype(str).str.strip()
dfTempID['in_WaterSourceTypeCV'] = outdf['in_WaterSourceTypeCV'].astype(str).str.strip()
dfTempID = dfTempID.drop_duplicates()

dfTempCount = pd.DataFrame(index=dfTempID.index)
dfTempCount["Count"] = range(1, len(dfTempCount.index) + 1)
dfTempID['in_WaterSourceNativeID'] = dfTempCount.apply(lambda row: assignIdValueFunc(row['Count']), axis=1)
dfTempID['linkKey'] = dfTempID['in_WaterSourceName'].astype(str) + dfTempID['in_WaterSourceTypeCV'].astype(str)
IdDict = pd.Series(dfTempID.in_WaterSourceNativeID.values, index=dfTempID.linkKey.astype(str)).to_dict()
# ----------------------------------------------------------------------------------------------------

# Retreive WaDE Custom site native ID
def retrieveIdValueFunc(checkVal, valA, valB):
    checkVal = str(checkVal).strip()
    if checkVal == "":
        linkKeyVal = str(valA).strip() + str(valB).strip()
        outString = IdDict[linkKeyVal]
    else:
        outString = checkVal
    return outString

outdf['in_WaterSourceNativeID'] = outdf.apply(lambda row: retrieveIdValueFunc(row['in_WaterSourceNativeID'], 
                                                                              row['in_WaterSourceName'], row['in_WaterSourceTypeCV']), axis=1)
outdf['in_WaterSourceNativeID'].unique()

array(['wadeId1', 'wadeId2', 'wadeId3', ..., 'wadeId8917', 'wadeId8918',
       'wadeId8919'], shape=(8919,), dtype=object)

In [44]:
# Creating WaDE Custom site native ID for easy site identification
# use Unique Latitude, Longitude, SiteName and SiteTypeCV values
# ----------------------------------------------------------------------------------------------------

# Create temp in_SiteNativeID dataframe of unique water source.
def assignIdValueFunc(colRowValue):
    string1 = str(colRowValue)
    outstring = "wadeId" + string1
    return outstring

dfTempID = pd.DataFrame()
dfTempID['in_Latitude'] = outdf['in_Latitude'].astype(str).str.strip()
dfTempID['in_Longitude'] = outdf['in_Longitude'].astype(str).str.strip()
dfTempID['in_SiteName'] = outdf['in_SiteName'].astype(str).str.strip()
dfTempID['in_SiteTypeCV'] = outdf['in_SiteTypeCV'].astype(str).str.strip()
dfTempID = dfTempID.drop_duplicates()

dfTempCount = pd.DataFrame(index=dfTempID.index)
dfTempCount["Count"] = range(1, len(dfTempCount.index) + 1)
dfTempID['in_SiteNativeID'] = dfTempCount.apply(lambda row: assignIdValueFunc(row['Count']), axis=1)
dfTempID['linkKey'] = dfTempID['in_Latitude'].astype(str) + dfTempID['in_Longitude'].astype(str) + dfTempID['in_SiteName'].astype(str)+ dfTempID['in_SiteTypeCV'].astype(str)
IdDict = pd.Series(dfTempID.in_SiteNativeID.values, index=dfTempID.linkKey.astype(str)).to_dict()
# ----------------------------------------------------------------------------------------------------

# Retreive WaDE Custom site native ID
def retrieveIdValueFunc(checkVal, valA, valB, valC, valD):
    checkVal = str(checkVal).strip()
    if checkVal == "":
        linkKeyVal = str(valA).strip() + str(valB).strip() + str(valC).strip() + str(valD).strip()
        outString = IdDict[linkKeyVal]
    else:
        outString = checkVal
    return outString

outdf['in_SiteNativeID'] = outdf.apply(lambda row: retrieveIdValueFunc(row['in_SiteNativeID'], 
                                                                       row['in_Latitude'], row['in_Longitude'],
                                                                       row['in_SiteName'], row['in_SiteTypeCV']), axis=1)
outdf['in_SiteNativeID'].unique()

array(['60497', '60498', '404', ..., '89194', '89195', '89196'],
      shape=(67192,), dtype=object)

## Drop non-Active AllocationLegalStatusCV Water Rights
- For CA, we don't want water rights that are considered: "Cancelled", "Closed", "Inactive", "Pending", "Rejected", "Revoked"

In [45]:
# drop non-active AllocationLegalStatusCV values specific to that state.

print(f'length of df before removing non-active rights: ', len(outdf))

# drop list
dropLegalStatusList = ["Cancelled", "Closed", "Inactive", "Pending", "Rejected", "Revoked"]

# drop rows from above list
outdf = outdf[outdf.in_AllocationLegalStatusCV.isin(dropLegalStatusList) == False].reset_index(drop=True)

print(f'length of df after removing non-active rights: ', len(outdf))
for x in outdf['in_AllocationLegalStatusCV'].sort_values().unique():
    print(f'"' + x + '",')

length of df before removing non-active rights:  2997930
length of df after removing non-active rights:  2946234
"",
"Active",
"Adjudicated",
"Certified",
"Claimed",
"Claimed - Local Oversight",
"Completed",
"Licensed",
"Permitted",
"Registered",

## Shapefile Data
- For attaching geometry to POU csv inputs.

In [46]:
# N/A

## Export Outputs

In [47]:
outdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2946234 entries, 0 to 2946233
Data columns (total 76 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   WaDEUUID                                      object
 1   in_MethodUUID                                 object
 2   in_VariableSpecificUUID                       object
 3   in_AggregationIntervalUnitCV                  object
 4   in_VariableCV                                 object
 5   in_OrganizationUUID                           object
 6   in_Geometry                                   object
 7   in_GNISFeatureNameCV                          object
 8   in_WaterQualityIndicatorCV                    object
 9   in_WaterSourceName                            object
 10  in_WaterSourceNativeID                        object
 11  in_WaterSourceTypeCV                          object
 12  in_OverlayUUIDs                               object
 13  in_WaterSourceUUID                            object
 14  in_CoordinateAccuracy                         object
 15  in_CoordinateMethodCV                         object
 16  in_County                                     object
 17  in_EPSGCodeCV                                 int64
 18  in_GNISCodeCV                                 object
 19  in_HUC12                                      object
 20  in_HUC8                                       object
 21  in_Latitude                                   object
 22  in_Longitude                                  object
 23  in_NHDNetworkStatusCV                         object
 24  in_NHDProductCV                               object
 25  in_PODorPOUSite                               object
 26  in_SiteName                                   object
 27  in_SiteNativeID                               object
 28  in_SitePoint                                  object
 29  in_SiteTypeCV                                 object
 30  in_StateCV                                    object
 31  in_USGSSiteID                                 object
 32  in_AllocationApplicationDate                  object
 33  in_AllocationAssociatedConsumptiveUseSiteIDs  object
 34  in_AllocationAssociatedWithdrawalSiteIDs      object
 35  in_AllocationBasisCV                          object
 36  in_AllocationChangeApplicationIndicator       object
 37  in_AllocationCommunityWaterSupplySystem       object
 38  in_AllocationCropDutyAmount                   object
 39  in_AllocationExpirationDate                   object
 40  in_AllocationFlow_CFS                         object
 41  in_AllocationLegalStatusCV                    object
 42  in_AllocationNativeID                         object
 43  in_AllocationOwner                            object
 44  in_AllocationPriorityDate                     datetime64[ns]
 45  in_AllocationSDWISIdentifierCV                object
 46  in_AllocationTimeframeEnd                     object
 47  in_AllocationTimeframeStart                   object
 48  in_AllocationTypeCV                           object
 49  in_AllocationVolume_AF                        object
 50  in_BeneficialUseCategory                      object
 51  in_CommunityWaterSupplySystem                 object
 52  in_CropTypeCV                                 object
 53  in_CustomerTypeCV                             object
 54  in_DataPublicationDate                        object
 55  in_DataPublicationDOI                         object
 56  in_ExemptOfVolumeFlowPriority                 object
 57  in_GeneratedPowerCapacityMW                   object
 58  in_IrrigatedAcreage                           object
 59  in_IrrigationMethodCV                         object
 60  in_LegacyAllocationIDs                        object
 61  in_OwnerClassificationCV                      object
 62  in_PopulationServed                           object
 63  in_PowerType                                  object
 64  in_PrimaryBeneficialUseCategory               object
 65  in_SDWISIdentifierCV                          object
 66  in_WaterAllocationNativeURL                   object
 67  in_Amount                                     object
 68  in_AssociatedNativeAllocationIDs              object
 69  in_PowerGeneratedGWh                          object
 70  in_PrimaryUseCategory                         object
 71  in_ReportYearCV                               object
 72  in_SDWISIdentifier                            object
 73  in_TimeframeEnd                               datetime64[ns]
 74  in_TimeframeStart                             datetime64[ns]
 75  in_VariableSpecificCV                         object
dtypes: datetime64[ns](3), int64(1), object(72)
memory usage: 1.7+ GB

In [ ]:
outdf1 = outdf1.fillna("")
outdf1 = outdf1.fillna("")

In [48]:
outdf

,WaDEUUID,in_MethodUUID,in_VariableSpecificUUID,in_AggregationIntervalUnitCV,in_VariableCV,in_OrganizationUUID,in_Geometry,in_GNISFeatureNameCV,in_WaterQualityIndicatorCV,in_WaterSourceName,in_WaterSourceNativeID,in_WaterSourceTypeCV,in_OverlayUUIDs,in_WaterSourceUUID,in_CoordinateAccuracy,in_CoordinateMethodCV,in_County,in_EPSGCodeCV,in_GNISCodeCV,in_HUC12,in_HUC8,in_Latitude,in_Longitude,in_NHDNetworkStatusCV,in_NHDProductCV,in_PODorPOUSite,in_SiteName,in_SiteNativeID,in_SitePoint,in_SiteTypeCV,in_StateCV,in_USGSSiteID,in_AllocationApplicationDate,in_AllocationAssociatedConsumptiveUseSiteIDs,in_AllocationAssociatedWithdrawalSiteIDs,in_AllocationBasisCV,in_AllocationChangeApplicationIndicator,in_AllocationCommunityWaterSupplySystem,in_AllocationCropDutyAmount,in_AllocationExpirationDate,in_AllocationFlow_CFS,in_AllocationLegalStatusCV,in_AllocationNativeID,in_AllocationOwner,in_AllocationPriorityDate,in_AllocationSDWISIdentifierCV,in_AllocationTimeframeEnd,in_AllocationTimeframeStart,in_AllocationTypeCV,in_AllocationVolume_AF,in_BeneficialUseCategory,in_CommunityWaterSupplySystem,in_CropTypeCV,in_CustomerTypeCV,in_DataPublicationDate,in_DataPublicationDOI,in_ExemptOfVolumeFlowPriority,in_GeneratedPowerCapacityMW,in_IrrigatedAcreage,in_IrrigationMethodCV,in_LegacyAllocationIDs,in_OwnerClassificationCV,in_PopulationServed,in_PowerType,in_PrimaryBeneficialUseCategory,in_SDWISIdentifierCV,in_WaterAllocationNativeURL,in_Amount,in_AssociatedNativeAllocationIDs,in_PowerGeneratedGWh,in_PrimaryUseCategory,in_ReportYearCV,in_SDWISIdentifier,in_TimeframeEnd,in_TimeframeStart,in_VariableSpecificCV
0,in12,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Icy Spring No 1,wadeId3,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.57797,-118.28921,,,POD,,404,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,Juan Garcia Lopez,NaT,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,Domestic,0,,NaT,NaT,Water Right Use_Monthly_Domestic_WaDE Blank
1,in13,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Kerr Spring No 2,wadeId4,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.57797,-118.28921,,,POD,,17603,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,Juan Garcia Lopez,NaT,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,Domestic,0,,NaT,NaT,Water Right Use_Monthly_Domestic_WaDE Blank
2,in14,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Kerr Spring No 1,wadeId5,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.58017,-118.28921,,,POD,,29028,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,Juan Garcia Lopez,NaT,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,Domestic,0,,NaT,NaT,Water Right Use_Monthly_Domestic_WaDE Blank
3,in15,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Icy Spring No 2,wadeId6,WaDE Blank,,,,DD_NE,Los Angeles,4326,,180902061401,18090206,34.57797,-118.28921,,,POD,,34881,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000016,Juan Garcia Lopez,NaT,,12/31,1/1,Appropriative,,Domestic,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000016,,Domestic,0,,NaT,NaT,Water Right Use_Monthly_Domestic_WaDE Blank
4,in16,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,Sacramento River,wadeId7,Surface,,,,GIS_LL,Glenn,4326,,180201570704,18020157,39.78957,-122.05020,,,POD,,28034,,WaDE Blank,CA,,,,,,,,,,,Licensed,A000018,Glenncolusa Irrigation District,NaT,,11/1,3/1,Appropriative,,Irrigation,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,A000018,,Agriculture Irrigation,0,,NaT,NaT,Water Right Use_Monthly_Agriculture Irrigation...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2946229,in167204,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,,wadeId41,Surface,,,,,,4326,,0,0,,,,,POD,Corral Creek Ranch Diversion,89192,,WaDE Blank,CA,,2/28/2025,,,,,,,,,Claimed,S029296,Harrigan Family Living Trust,NaT,,,,Statement of Div and Use RIPARIAN PRE1914,,Irrigation,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,S029296,,Agriculture Irrigation,0,,NaT,NaT,Water Right Use_Monthly_Agriculture Irrigation...
2946230,in167205,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,,wadeId41,Surface,,,,,,4326,,0,0,,,,,POD,Wfi Pump,89193,,WaDE Blank,CA,,2/28/2025,,,,,,,,14.00000,Claimed,S029297,Wilcox Family Investments,NaT,,,,Statement of Div and Use RIPARIAN PRE1914 OTHER,,Irrigation,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,S029297,,Agriculture Irrigation,0,,NaT,NaT,Water Right Use_Monthly_Agriculture Irrigation...
2946231,in167206,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,,wadeId41,Surface,,,,,,4326,,0,0,,,,,POD,Wildhorse Well #2 Cauley,89194,,WaDE Blank,CA,,3/3/2025,,,,,,,,2.00521,Claimed,S029298,Jerry J Rava Ii Trust,NaT,,,,Statement of Div and Use RIPARIAN,,Irrigation,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,S029298,,Agriculture Irrigation,0,,NaT,NaT,Water Right Use_Monthly_Agriculture Irrigation...
2946232,in167207,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,,wadeId41,Surface,,,,,,4326,,0,0,,,,,POD,Harrell Ranch No 1,89195,,WaDE Blank,CA,,3/4/2025,,,,,,,,19.00000,Claimed,S029299,Jay Tevelde Jr,NaT,,,,Statement of Div and Use PRE1914,,Irrigation,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,S029299,,Agriculture Irrigation,0,,NaT,NaT,Water Right Use_Monthly_Agriculture Irrigation...
2946233,in167208,CSWRCBwrwu_M1,CSWRCBwrwu_V1,Monthly,Water Right Use,CSWRCBwrwu_O1,,,,,wadeId41,Surface,,,,,,4326,,0,0,,,,,POD,Mckay Ditch,89196,,WaDE Blank,CA,,3/4/2025,,,,,,,,,Claimed,S029300,Frank Hutchinson,NaT,,,,Statement of Div and Use PRE1914,,Other,,,,,,1,,,,,,,,,,https://ciwqs.waterboards.ca.gov/ciwqs/ewrims/...,,S029300,,Other,0,,NaT,NaT,Water Right Use_Monthly_Other_Surface

In [49]:
# Export the output dataframe
outdf.to_csv('RawInputData/Pwrwu_Main.zip', compression=dict(method='zip', archive_name='Pwrwu_Main.csv'), index=False)  # The output, save as a zip